export type LogicValueKind = "source-backed anchor" | "planning estimate" | "product constraint" | "athlete-entered value";

export type LogicTraceabilityEntry = {
  id: string;
  surface: string;
  kind: LogicValueKind;
  rationale: string;
  sourceUrls?: readonly string[];
  athleteBoundary: string;
};

const sources = {
  resistancePrescription: "https://bjsm.bmj.com/content/57/18/1211",
  hypertrophyLoadRange: "https://doi.org/10.1007/s40279-021-01558-1",
  rpeRir: "https://pmc.ncbi.nlm.nih.gov/articles/PMC4961270/",
  mechanicsUncertainty: "https://pubmed.ncbi.nlm.nih.gov/22507351/",
  coContractionBoundary: "https://pubmed.ncbi.nlm.nih.gov/31668905/",
} as const;

/**
 * Named model settings are intentionally separated from source-backed training
 * anchors. Their values make relative ordering stable; they are never direct
 * athlete measurements, universal physiological cutoffs, or prescriptions.
 */
export const logicCalibration = {
  sportDemand: {
    activePriority: 0.78,
    backgroundPriority: 0.32,
    modifierContextLift: 0.08,
    displayCap: 0.9,
    priorityFilter: 0.7,
  },
  recommendation: {
    signalMatchWeight: 2.25,
    muscleMatchWeight: 1.75,
    rotationalPowerBonus: 1.25,
    unilateralBonus: 1,
    sprintPowerAdjustmentCap: 1.2,
    goalAthleticismLift: 1.2,
    goalStrengthOrGrowthLift: 0.9,
    noveltySignalWeight: 2.2,
    noveltyMuscleWeight: 1.5,
    noveltyHierarchyWeight: 0.45,
    sameMovementPenalty: 6.2,
    overlapPenalty: 5.5,
    repeatedEquipmentPenalty: 0.7,
    resultLimit: 10,
    sessionLimit: 6,
    assistanceLimit: 8,
    assistanceFallbackLimit: 18,
  },
  movementProgramAnalysis: {
    displayScaleMaximum: 100,
    nonZeroCoverageDenominator: 1,
    displayedStrengthLimit: 3,
    displayedPriorityLimit: 3,
    closelySimilarMuscleOverlap: 0.72,
    closelySimilarQualityOverlap: 0.55,
    sameMovementMuscleOverlap: 0.5,
    reviewQualityOverlap: 0.6,
    minimumMatchWordLength: 4,
    minimumMatchWords: 2,
  },
  exerciseGenome: {
    relativeScaleMaximum: 100,
    relativeScaleMinimum: 0,
    highRedundancyReview: 62,
    highFatigueReview: 70,
    contextStabilityLift: 4,
    roleTierS: 88,
    roleTierA: 76,
    roleTierB: 62,
    roleTierC: 46,
    contextualGradeSS: 91,
    contextualGradeS: 82,
    contextualGradeA: 72,
    contextualGradeB: 60,
    contextualGradeC: 45,
    contextualGradeD: 28,
    muscleSimilarityWeight: 0.4,
    movementSimilarityWeight: 0.26,
    resistanceProfileSimilarityWeight: 0.14,
    qualitySimilarityWeight: 0.2,
    emptyStackRedundancyBaseline: 10,
    sportMuscleMatchWeight: 0.54,
    sportSignalMatchWeight: 0.3,
    sportStabilityMatchWeight: 0.16,
    systemicRecoveryCostWeight: 0.5,
    technicalRecoveryCostWeight: 0.25,
    axialRecoveryCostWeight: 0.25,
    contextualGoalWeight: 0.52,
    contextualDistinctnessWeight: 0.24,
    contextualSportWeight: 0.24,
  },
  fingerprint: {
    hypertrophyBase: 42,
    hypertrophyQualityPresent: 38,
    hypertrophyQualityAbsent: 8,
    hypertrophyMachineLift: 6,
    hypertrophyIsolationLift: 5,
    strengthBase: 34,
    strengthQualityPresent: 45,
    strengthQualityAbsent: 10,
    strengthFreeWeightLift: 8,
    strengthBarbellPatternLift: 8,
    powerBase: 12,
    powerQualityPresent: 56,
    powerQualityAbsent: 8,
    powerBallisticLift: 18,
    powerJumpingLift: 10,
    stabilityBase: 22,
    stabilityBracingPresent: 32,
    stabilityBracingAbsent: 8,
    stabilityUnilateralLift: 20,
    stabilityFreeWeightLift: 10,
    mobilityBase: 20,
    mobilityDeepRangeLift: 40,
    mobilityStandardRangeLift: 14,
    mobilityUnilateralLift: 8,
    skillBase: 18,
    skillFreeWeightLift: 16,
    skillNonFreeWeightLift: 4,
    skillUnilateralLift: 15,
    skillBallisticLift: 18,
    skillComplexLift: 22,
    fatigueBase: 25,
    fatigueStrengthThreshold: 75,
    fatigueStrengthLift: 25,
    fatigueBallisticLift: 12,
    fatigueAxialPatternLift: 18,
    fatigueUnilateralLift: 6,
    practicalityBase: 84,
    practicalityMachineCost: 18,
    practicalityRackCost: 16,
    practicalityComplexCost: 9,
    stimulusFatigueMultiplier: 0.34,
    stimulusFatigueBase: 30,
    fatigueBaseOffset: 16,
    systemicStrengthLift: 12,
    systemicNonStrengthOffset: -4,
    gripTaskBase: 62,
    gripDefaultBase: 16,
    gripStrengthLift: 8,
    axialTaskBase: 70,
    axialDefaultBase: 22,
    setupBodyweightLift: 9,
    spaceLocomotionCost: 32,
    homeGymMachineCost: 34,
    supersetEaseBase: 90,
    supersetFatigueMultiplier: 0.62,
  },
  targeting: {
    primeMoverPrior: 78,
    synergistPrior: 50,
    stabilizerPrior: 30,
    directEvidenceRelativeFloor: 82,
    jointAngleFullRomSignal: 72,
    jointAngleLongLengthSignal: 78,
    jointAngleIndividualizedSignal: 64,
    jointAngleFallbackSignal: 58,
    cableForceVectorSignal: 73,
    guidedForceVectorSignal: 63,
    gravityForceVectorSignal: 68,
    broadMomentSignal: 74,
    defaultMomentSignal: 58,
    focusedMomentArmSignal: 68,
    compoundMomentArmSignal: 64,
    defaultMomentArmSignal: 56,
    majorArchitectureSignal: 66,
    defaultArchitectureSignal: 56,
    lengthenedForceLengthSignal: 82,
    shortenedForceLengthSignal: 50,
    defaultForceLengthSignal: 62,
    ballisticForceVelocitySignal: 86,
    defaultForceVelocitySignal: 54,
    eccentricContractionSignal: 82,
    ballisticContractionSignal: 68,
    defaultContractionSignal: 58,
    biarticularSignal: 72,
    nonBiarticularSignal: 50,
    unilateralStabilizerSignal: 82,
    stabilizerSignal: 66,
    unilateralSynergistSignal: 68,
    defaultStabilizationSignal: 48,
    rolePriorWeight: 0.5,
    mechanicsFactorsWeight: 0.5,
  },
  exposure: {
    secondarySetConvention: 0.5,
    primaryRoleWeight: 1,
    synergistRoleWeight: 0.65,
    stabilizerRoleWeight: 0.4,
    lowDirectSetBand: 6,
    highDirectSetBand: 12,
    consecutiveDayMinimumSets: 3,
    consecutiveDayPriorityExposure: 8,
    splitCoverageGapRatio: 0.65,
    splitCoverageHighOffset: 35,
    splitPrimaryTagWeight: 56,
    splitSupportTagWeight: 24,
  },
  progression: {
    relativePerformanceRepNormalizer: 30,
    mediumConfidenceSessions: 2,
    highConfidenceSessions: 3,
    substantialDownwardChange: -0.1,
    maintainPerformanceTolerance: -0.03,
    highEffortRpe: 9,
    holdEffortRpe: 9.5,
  },
  segmentProgress: {
    loadIncreaseSignal: 2,
    repetitionIncreaseSignal: 1,
    holdSignal: -1,
    loadReductionSignal: -2,
    progressingAverageSignal: 0.75,
    reviewAverageSignal: -0.75,
    neutralIndex: 50,
    displayMultiplier: 25,
  },
  workoutReview: {
    defaultPrescriptionSets: 3,
    defaultRestSeconds: 90,
    defaultRpe: 7,
    highRedundancyReview: 62,
    highFatigueReview: 72,
    moderateFatigueReview: 52,
    shortStrengthRestSeconds: 150,
    highAthleticismRpe: 9,
    unusedTimeMinutes: 18,
    broadPatternGapCount: 4,
    defaultGymMinutes: 60,
  },
  mobility: {
    athleticismRehearseBoost: 1.8,
    athleticismRaiseBoost: 0.8,
    strengthActivateBoost: 1.4,
    strengthRehearseBoost: 1.1,
    hypertrophyMobilizeBoost: 1.15,
    hypertrophyActivateBoost: 0.8,
    capacityRaiseBoost: 1.25,
    capacityRehearseBoost: 0.75,
    matchedTagWeight: 2.45,
    directTagBoost: 1.25,
    focusTagLimit: 7,
    automaticPhaseSelectionCount: 4,
    minimumDistinctDrillsBeforeRepeat: 4,
    targetPhaseCount: 4,
    maximumDrills: 6,
    fallbackDrillCount: 5,
  },
} as const;

export const evidenceTraceability: readonly LogicTraceabilityEntry[] = [
  {
    id: "programming-anchors",
    surface: "Training Days prescriptions, repetitions, volume, and rest guidance",
    kind: "source-backed anchor",
    rationale: "Population-level resistance-training evidence informs the available planning ranges; the app keeps them editable and does not treat them as personal optima.",
    sourceUrls: [sources.resistancePrescription, sources.hypertrophyLoadRange],
    athleteBoundary: "A planning anchor is not a required dose, individual response prediction, or health assessment.",
  },
  {
    id: "rpe-log-context",
    surface: "Workout logging and progression review",
    kind: "source-backed anchor",
    rationale: "RPE/RIR is a recorded subjective effort context used to hold or review progression, not to diagnose readiness.",
    sourceUrls: [sources.rpeRir],
    athleteBoundary: "Recorded RPE is athlete-reported context, not a physiological measurement or medical signal.",
  },
  {
    id: "progression-review-guards",
    surface: "Progression cards, session history, and segment review",
    kind: "planning estimate",
    rationale: "Comparable-session count, trend, and high-effort guards make a conservative suggestion workflow possible without treating a short log as a physiological test.",
    sourceUrls: [sources.rpeRir],
    athleteBoundary: "Progression guards trigger review or an athlete-approved note; they do not prescribe a mandatory load change or diagnose recovery.",
  },
  {
    id: "relative-model-calibration",
    surface: "Exercise Genome, sport recommendations, stack analysis, and muscle targeting",
    kind: "planning estimate",
    rationale: "Named calibration constants stabilize relative ordering across catalog records where studies support factors and boundaries but not a universal composite score.",
    sourceUrls: [sources.mechanicsUncertainty, sources.coContractionBoundary],
    athleteBoundary: "Relative model values compare configured catalog context only; they are not EMG, force, readiness, injury risk, or guaranteed transfer measurements.",
  },
  {
    id: "schedule-and-interface-constraints",
    surface: "Gym-time options, catalog limits, list limits, and empty states",
    kind: "product constraint",
    rationale: "These values make the interface usable and are not represented as training-science findings.",
    athleteBoundary: "A product constraint is adjustable interface behavior, not an exercise or athlete recommendation.",
  },
  {
    id: "server-validation-and-security-constraints",
    surface: "Account security, input validation, session duration, history retrieval, and set-log field bounds",
    kind: "product constraint",
    rationale: "Authentication, storage, API validation, and history-window numbers defend service reliability and valid records; they are not training recommendations or evidence claims.",
    athleteBoundary: "Security and validation limits do not characterize athlete ability, prescribe a dose, or establish a clinical threshold.",
  },
  {
    id: "catalog-and-movement-ranks",
    surface: "Catalog IDs, catalog ranks, sport cues, movement coverage, overlap review, and assistance-list ordering",
    kind: "planning estimate",
    rationale: "Catalog taxonomy and source-backed movement records inform an ordinal relevance and coverage workflow; exact ranks, review thresholds, and list sizes remain configured planning rules.",
    sourceUrls: [sources.mechanicsUncertainty, sources.coContractionBoundary],
    athleteBoundary: "Catalog and movement ranks are comparative navigation aids, not measurements of activation, performance, readiness, recovery, or exercise value for an individual.",
  },
  {
    id: "research-record-governance",
    surface: "Research record status, eligibility, absent-field handling, and cited protocol/result values",
    kind: "product constraint",
    rationale: "Study-specific numbers remain attached to their source record and scope; database eligibility and missing-field behavior govern transparent display rather than prove a recommendation.",
    athleteBoundary: "A cited study result is population- and protocol-specific. A blank or unavailable source field is shown as unavailable, never as a favorable or unfavorable athlete result.",
  },
  {
    id: "session-and-history-display",
    surface: "Set-log controls, completion counts, session history, trend cards, and formatted catalog or workout identifiers",
    kind: "athlete-entered value",
    rationale: "Weights, repetitions, RPE, completion state, and session counts are stored athlete observations; display precision, pagination, and defaults are interface rules around those records.",
    athleteBoundary: "Logged observations support comparison with the athlete’s own history and are not automatically converted into readiness, strength, health, or cross-athlete rankings.",
  },
  {
    id: "logged-athlete-observations",
    surface: "Load, repetitions, RPE, session completion, optional bodyweight, and saved prescriptions",
    kind: "athlete-entered value",
    rationale: "The app stores these observations to compare the athlete with their own prior comparable logs.",
    athleteBoundary: "Logged observations are not converted into a diagnosis, body-composition estimate, or cross-person ranking.",
  },
] as const;

export function getLogicTraceability(id: string) {
  return evidenceTraceability.find((entry) => entry.id === id);
}
