/**
 * Exercise photographs.
 *
 * The photos are the Free Exercise DB set (github.com/yuhonas/free-exercise-db,
 * public domain under the Unlicense), the same records Hugging Face mirrors as
 * the `sirnino/bodybuilding-exercises` dataset. Each exercise there has two
 * photographs, the start and the finish of the movement, taken with one model
 * against one background, so a pair reads as one exercise rather than two
 * stock images.
 *
 * `client/src/data/exercisePhotos.json` maps this catalog's exercise ids to the
 * source exercise: its folder id, how many frames it has, and the frames'
 * intrinsic size. It is generated by `scripts/exercise-photos/curate.mjs`
 * (exact name matches plus a hand-checked alias table, never a fuzzy guess - a
 * wrong photo teaches a wrong movement) and `dimensions.mjs` (the sizes, read
 * from the files at the pinned commit). An exercise the source does not
 * photograph has no entry and shows a placeholder, never another exercise's photo.
 *
 * The files are served from the jsDelivr GitHub CDN, which caches the repository
 * at a pinned commit; nothing is fetched at build time and the bundle carries
 * only the map.
 */
import mapping from "@/data/exercisePhotos.json";

/** Pinned so a later change upstream cannot swap a photo out from under a name. */
export const exercisePhotoSourceRef = "f00c92c7dcf1216a928a52c3706c7ce8e2f71ed5";
export const exercisePhotoSourceRepo = "yuhonas/free-exercise-db";
export const exercisePhotoBase = `https://cdn.jsdelivr.net/gh/${exercisePhotoSourceRepo}@${exercisePhotoSourceRef}/exercises/`;
/** A second host for the same bytes, used when the CDN cannot be reached. */
export const exercisePhotoFallbackBase = `https://raw.githubusercontent.com/${exercisePhotoSourceRepo}/${exercisePhotoSourceRef}/exercises/`;

export const exercisePhotoCredit = "Photos: Free Exercise DB, public domain";

/**
 * The source photographs are landscape, 3:2, with the model centred. Every
 * frame the app draws is the photograph's own shape, so nothing is cropped
 * away; `focal` is where a frame of another shape would centre, kept with the
 * record for the day one is wanted.
 */
export type ExercisePhotoSet = {
  /** The source folder, e.g. "Barbell_Deadlift". */
  source: string;
  /** Start and finish frames, in order; one frame for a hold. */
  urls: string[];
  fallbackUrls: string[];
  captions: string[];
  /** Intrinsic pixel size of the frames, for reserving the box before the bytes arrive. */
  width: number;
  height: number;
  /** CSS object-position for a frame of another shape. */
  focal: string;
};

type Entry = [string, number] | [string, number, number, number];
const entries = mapping as unknown as Record<string, Entry>;

/** The source's usual frame, for the few entries whose size has not been read. */
const defaultSize = { width: 850, height: 567 };

/** Per-photo focal points for the rare frame whose subject is off centre, by source id. */
const focalBySource: Record<string, string> = {};

export function exercisePhotoSet(exerciseId: number): ExercisePhotoSet | null {
  const entry = entries[String(exerciseId)];
  if (!entry) return null;
  const [source, count, width = defaultSize.width, height = defaultSize.height] = entry;
  const frames = Array.from({ length: Math.max(1, Math.min(count, 2)) }, (_, index) => index);
  return {
    source,
    urls: frames.map((index) => `${exercisePhotoBase}${source}/${index}.jpg`),
    fallbackUrls: frames.map((index) => `${exercisePhotoFallbackBase}${source}/${index}.jpg`),
    captions: frames.length === 1 ? ["Position"] : ["Start", "Finish"],
    width,
    height,
    focal: focalBySource[source] ?? "50% 50%",
  };
}

/** How many of the catalog's exercises have a photograph, for the record and its tests. */
export const exercisePhotoCount = Object.keys(entries).length;
