/**
 * Exercise photographs.
 *
 * The photos are the Free Exercise DB set (github.com/yuhonas/free-exercise-db,
 * public domain under the Unlicense), the same records Hugging Face mirrors as
 * the `sirnino/bodybuilding-exercises` dataset. Each exercise there has two
 * photographs, the start and the finish of the movement, taken with one model
 * against one background, so a pair reads as one exercise rather than two
 * stock images.
 *
 * `client/src/data/exercisePhotos.json` maps this catalog's exercise ids to the
 * source exercise: its folder id, how many frames it has, and the frames'
 * intrinsic size. It is generated by `scripts/exercise-photos/curate.mjs`
 * (exact name matches plus a hand-checked alias table, never a fuzzy guess - a
 * wrong photo teaches a wrong movement) and `dimensions.mjs` (the sizes, read
 * from the files at the pinned commit). An exercise the source does not
 * photograph has no entry and shows a placeholder, never another exercise's photo.
 *
 * The full frames are served from the jsDelivr GitHub CDN, which caches the
 * repository at a pinned commit. A row's thumbnail is a same-origin copy of the
 * start frame, scaled for an 88-pixel frame at 3x (`client/public/exercise-thumbs/`,
 * made by `scripts/exercise-photos/thumbnails.mjs`; where each came from, with
 * checksums, is docs/exercise-media-audit/sources.json), so a list of rows no
 * longer downloads a 850-pixel photograph per row from a third party.
 *
 * The source's frame numbers are not always the movement's order: in 30 of the
 * 231 pairs audited (29 still in use), frame 0 is where the movement finishes (a cable lateral
 * raise with the arm already up, a dip at the bottom). Every pair was checked
 * by eye against how the exercise starts, and the reversed ones are listed in
 * `client/src/data/exercisePhotoOrder.json` with the reason; for those the app
 * shows frame 1 first. The audit of all 231 is docs/exercise-photo-order/.
 */
import mapping from "@/data/exercisePhotos.json";
import drillMapping from "@/data/drillPhotos.json";
import reversedOrder from "@/data/exercisePhotoOrder.json";

/** Pinned so a later change upstream cannot swap a photo out from under a name. */
export const exercisePhotoSourceRef = "f00c92c7dcf1216a928a52c3706c7ce8e2f71ed5";
export const exercisePhotoSourceRepo = "yuhonas/free-exercise-db";
export const exercisePhotoBase = `https://cdn.jsdelivr.net/gh/${exercisePhotoSourceRepo}@${exercisePhotoSourceRef}/exercises/`;
/** A second host for the same bytes, used when the CDN cannot be reached. */
export const exercisePhotoFallbackBase = `https://raw.githubusercontent.com/${exercisePhotoSourceRepo}/${exercisePhotoSourceRef}/exercises/`;

/** Same-origin thumbnails of the start frames, one per source folder. */
export const exerciseThumbBase = `${import.meta.env?.BASE_URL ?? "/"}exercise-thumbs/`;

export const exercisePhotoCredit = "Photos: Free Exercise DB, public domain";

/**
 * The source photographs are landscape, 3:2, with the model centred. Every
 * frame the app draws is the photograph's own shape, so nothing is cropped
 * away; `focal` is where a frame of another shape would centre, kept with the
 * record for the day one is wanted.
 */
export type ExercisePhotoSet = {
  /** The source folder, e.g. "Barbell_Deadlift". */
  source: string;
  /** Start and finish frames, in the movement's order (not always the source's numbering); one frame for a hold. */
  urls: string[];
  fallbackUrls: string[];
  /** The start frame scaled for a row's thumbnail, served from this app's own origin. */
  thumbUrl: string;
  captions: string[];
  /** Intrinsic pixel size of the frames, for reserving the box before the bytes arrive. */
  width: number;
  height: number;
  /** CSS object-position for a frame of another shape. */
  focal: string;
};

type Entry = [string, number] | [string, number, number, number];
const entries = mapping as unknown as Record<string, Entry>;
/**
 * The warm-up library's drills and stretches (preTrainingMobility.ts), by drill id, from the
 * same source and checked the same way: a drill gets a photo only where the source shows
 * that drill - its position, its equipment and its action - never a cousin for the same
 * region. Generated by scripts/exercise-photos/drills.mjs; docs/drill-photos/.
 */
const drillEntries = drillMapping as unknown as Record<string, Entry>;

/** The source's usual frame, for the few entries whose size has not been read. */
const defaultSize = { width: 850, height: 567 };

/** Per-photo focal points for the rare frame whose subject is off centre, by source id. */
const focalBySource: Record<string, string> = {};

/** Source pairs whose frame 0 is the finish, by source id, with why (exercisePhotoOrder.json). */
export const reversedPhotoSources: Readonly<Record<string, string>> = reversedOrder;

/** The source's frame numbers in the movement's order: start first, then finish. */
export function framesInMovementOrder(source: string, count: number): number[] {
  const frames = Array.from({ length: Math.max(1, Math.min(count, 2)) }, (_, index) => index);
  return frames.length === 2 && reversedPhotoSources[source] ? [1, 0] : frames;
}

export function exercisePhotoSet(exerciseId: number): ExercisePhotoSet | null {
  return photoSetFor(entries[String(exerciseId)]);
}

/** A warm-up drill's photographs, by its id in the preparation library. */
export function drillPhotoSet(drillId: string): ExercisePhotoSet | null {
  return photoSetFor(Object.prototype.hasOwnProperty.call(drillEntries, drillId) ? drillEntries[drillId] : undefined);
}

function photoSetFor(entry: Entry | undefined): ExercisePhotoSet | null {
  if (!entry) return null;
  const [source, count, width = defaultSize.width, height = defaultSize.height] = entry;
  const frames = framesInMovementOrder(source, count);
  return {
    source,
    urls: frames.map((index) => `${exercisePhotoBase}${source}/${index}.jpg`),
    fallbackUrls: frames.map((index) => `${exercisePhotoFallbackBase}${source}/${index}.jpg`),
    thumbUrl: `${exerciseThumbBase}${encodeURIComponent(source)}.jpg`,
    captions: frames.length === 1 ? ["Position"] : ["Start", "Finish"],
    width,
    height,
    focal: focalBySource[source] ?? "50% 50%",
  };
}

/** How many of the catalog's exercises have a photograph, for the record and its tests. */
export const exercisePhotoCount = Object.keys(entries).length;
/** How many of the warm-up library's drills have a photograph. */
export const drillPhotoCount = Object.keys(drillEntries).length;
