import type { Exercise, Grade, Sport } from "./exerciseCatalog";

type CatalogInput = Omit<Exercise, "id" | "sportFit"> & {
  sportEmphasis: Sport;
  sportGrade: Grade;
  sportCue: string;
};

const defaultCues: Record<Sport, string> = {
  tennis: "rotation and court-position support",
  basketball: "contact and court-control support",
  soccer: "running and contact support",
  baseball: "rotation and arm-path support",
  combat: "stance, grip, and force-transfer support",
};

function gradeFor(base: Grade, emphasis: Sport, sport: Sport): Grade {
  if (sport === emphasis) return base;
  if (base === "SS" || base === "S") return "A";
  if (base === "A") return "B";
  return "C";
}

function sportFit(input: CatalogInput): Exercise["sportFit"] {
  const build = (sport: Sport) => ({
    grade: gradeFor(input.sportGrade, input.sportEmphasis, sport),
    movementHelp: sport === input.sportEmphasis ? input.sportCue : defaultCues[sport],
  });
  return { tennis: build("tennis"), basketball: build("basketball"), soccer: build("soccer"), baseball: build("baseball"), combat: build("combat") };
}

const cablePressing: CatalogInput[] = [
  { name: "Cable Press Around", sourceGroup: "Cable — Sport Transfer Expansion", category: "Chest & push", equipment: "Cable", movement: "Horizontal push", primaryMuscles: ["chest"], secondaryMuscles: ["frontDelts", "triceps", "abs"], qualities: ["strength", "hypertrophy", "bracing"], muscleGrade: "A", sportEmphasis: "combat", sportGrade: "A", sportCue: "angled pushing and torso bracing" },
  { name: "Split-Stance Cable Chest Press", sourceGroup: "Cable — Sport Transfer Expansion", category: "Chest & push", equipment: "Cable", movement: "Horizontal push", primaryMuscles: ["chest"], secondaryMuscles: ["triceps", "frontDelts", "obliques", "glutes"], qualities: ["strength", "unilateral", "bracing", "antiRotation"], muscleGrade: "A", sportEmphasis: "combat", sportGrade: "A", sportCue: "split-stance pressing and bracing" },
  { name: "Half-Kneeling Cable Chest Press", sourceGroup: "Cable — Sport Transfer Expansion", category: "Chest & push", equipment: "Cable", movement: "Horizontal push", primaryMuscles: ["chest"], secondaryMuscles: ["triceps", "frontDelts", "obliques", "glutes"], qualities: ["strength", "bracing", "antiRotation"], muscleGrade: "A", sportEmphasis: "baseball", sportGrade: "A", sportCue: "trunk-controlled unilateral pressing" },
  { name: "Cable Squeeze Press", sourceGroup: "Cable — Sport Transfer Expansion", category: "Chest & push", equipment: "Cable", movement: "Horizontal push", primaryMuscles: ["chest"], secondaryMuscles: ["triceps", "frontDelts"], qualities: ["hypertrophy", "strength"], muscleGrade: "A", sportEmphasis: "basketball", sportGrade: "B", sportCue: "controlled close-range pressing" },
  { name: "Cable Incline Press", sourceGroup: "Cable — Sport Transfer Expansion", category: "Chest & push", equipment: "Cable", movement: "Diagonal push", primaryMuscles: ["chest", "frontDelts"], secondaryMuscles: ["triceps", "abs"], qualities: ["strength", "hypertrophy", "bracing"], muscleGrade: "A", sportEmphasis: "basketball", sportGrade: "A", sportCue: "upward pressing and finishing force" },
  { name: "Cable Decline Press", sourceGroup: "Cable — Sport Transfer Expansion", category: "Chest & push", equipment: "Cable", movement: "Diagonal push", primaryMuscles: ["chest"], secondaryMuscles: ["triceps", "frontDelts", "abs"], qualities: ["strength", "hypertrophy", "bracing"], muscleGrade: "A", sportEmphasis: "combat", sportGrade: "B", sportCue: "downward pressing control and bracing" },
  { name: "Neutral-Grip Cable Chest Press", sourceGroup: "Cable — Sport Transfer Expansion", category: "Chest & push", equipment: "Cable", movement: "Horizontal push", primaryMuscles: ["chest"], secondaryMuscles: ["triceps", "frontDelts", "abs"], qualities: ["strength", "hypertrophy", "bracing"], muscleGrade: "A", sportEmphasis: "combat", sportGrade: "A", sportCue: "close-range pushing and hand-fighting support" },
  { name: "Single-Arm Cable Floor Press", sourceGroup: "Cable — Sport Transfer Expansion", category: "Chest & push", equipment: "Cable", movement: "Horizontal push", primaryMuscles: ["chest"], secondaryMuscles: ["triceps", "frontDelts", "obliques"], qualities: ["strength", "unilateral", "antiRotation"], muscleGrade: "A", sportEmphasis: "combat", sportGrade: "A", sportCue: "unilateral press force with trunk control" },
  { name: "Cable Resisted Push-Up", sourceGroup: "Cable — Sport Transfer Expansion", category: "Chest & push", equipment: "Cable", movement: "Horizontal push", primaryMuscles: ["chest", "triceps"], secondaryMuscles: ["frontDelts", "abs", "glutes"], qualities: ["strength", "power", "bracing"], muscleGrade: "A", sportEmphasis: "combat", sportGrade: "A", sportCue: "whole-body pushing and frames" },
  { name: "Cable Press-Out", sourceGroup: "Cable — Sport Transfer Expansion", category: "Chest & push", equipment: "Cable", movement: "Anti-rotation press", primaryMuscles: ["abs", "obliques"], secondaryMuscles: ["chest", "triceps", "frontDelts"], qualities: ["antiRotation", "bracing", "unilateral"], muscleGrade: "S", sportEmphasis: "baseball", sportGrade: "A", sportCue: "stable trunk force transfer" },
  { name: "Single-Arm Cable Fly", sourceGroup: "Cable — Sport Transfer Expansion", category: "Chest & push", equipment: "Cable", movement: "Horizontal push", primaryMuscles: ["chest"], secondaryMuscles: ["frontDelts", "obliques", "abs"], qualities: ["hypertrophy", "unilateral", "antiRotation"], muscleGrade: "A", sportEmphasis: "tennis", sportGrade: "B", sportCue: "unilateral arm-path and trunk control" },
  { name: "Cable Incline Fly", sourceGroup: "Cable — Sport Transfer Expansion", category: "Chest & push", equipment: "Cable", movement: "Diagonal push", primaryMuscles: ["chest"], secondaryMuscles: ["frontDelts", "abs"], qualities: ["hypertrophy", "coordination"], muscleGrade: "A", sportEmphasis: "basketball", sportGrade: "B", sportCue: "upward arm-path capacity" },
  { name: "Cable Decline Fly", sourceGroup: "Cable — Sport Transfer Expansion", category: "Chest & push", equipment: "Cable", movement: "Diagonal push", primaryMuscles: ["chest"], secondaryMuscles: ["frontDelts", "abs"], qualities: ["hypertrophy", "coordination"], muscleGrade: "A", sportEmphasis: "combat", sportGrade: "B", sportCue: "low-angle pushing capacity" },
  { name: "Cable Reverse Fly Cross", sourceGroup: "Cable — Sport Transfer Expansion", category: "Shoulders & posture", equipment: "Cable", movement: "Horizontal pull", primaryMuscles: ["rearDelts", "upperBack"], secondaryMuscles: ["traps", "rotatorCuff"], qualities: ["scapularControl", "endurance"], muscleGrade: "S", sportEmphasis: "baseball", sportGrade: "A", sportCue: "posterior shoulder and arm-deceleration support" },
  { name: "Cable Y Raise", sourceGroup: "Cable — Sport Transfer Expansion", category: "Shoulders & posture", equipment: "Cable", movement: "Overhead control", primaryMuscles: ["traps", "rotatorCuff"], secondaryMuscles: ["rearDelts", "abs"], qualities: ["scapularControl", "endurance"], muscleGrade: "S", sportEmphasis: "baseball", sportGrade: "A", sportCue: "overhead scapular-control capacity" },
  { name: "Cable Scaption Raise", sourceGroup: "Cable — Sport Transfer Expansion", category: "Shoulders & posture", equipment: "Cable", movement: "Overhead control", primaryMuscles: ["sideDelts", "frontDelts"], secondaryMuscles: ["traps", "rotatorCuff"], qualities: ["scapularControl", "endurance"], muscleGrade: "A", sportEmphasis: "tennis", sportGrade: "A", sportCue: "shoulder elevation control for serving" },
  { name: "Cable Upright Row", sourceGroup: "Cable — Sport Transfer Expansion", category: "Shoulders & posture", equipment: "Cable", movement: "Vertical pull", primaryMuscles: ["sideDelts", "traps"], secondaryMuscles: ["biceps", "forearms"], qualities: ["hypertrophy", "strength"], muscleGrade: "A", sportEmphasis: "basketball", sportGrade: "B", sportCue: "upper-body contact and arm-drive support" },
  { name: "Cable Rear-Delt Row", sourceGroup: "Cable — Sport Transfer Expansion", category: "Shoulders & posture", equipment: "Cable", movement: "Horizontal pull", primaryMuscles: ["rearDelts", "upperBack"], secondaryMuscles: ["traps", "biceps"], qualities: ["scapularControl", "strength"], muscleGrade: "S", sportEmphasis: "baseball", sportGrade: "A", sportCue: "posterior shoulder control and deceleration" },
  { name: "Cable Cuban Rotation", sourceGroup: "Cable — Sport Transfer Expansion", category: "Shoulders & posture", equipment: "Cable", movement: "External rotation", primaryMuscles: ["rotatorCuff", "rearDelts"], secondaryMuscles: ["traps", "forearms"], qualities: ["scapularControl", "endurance"], muscleGrade: "S", sportEmphasis: "baseball", sportGrade: "A", sportCue: "rotator-cuff and overhead-control support" },
  { name: "Cable 90/90 External Rotation", sourceGroup: "Cable — Sport Transfer Expansion", category: "Shoulders & posture", equipment: "Cable", movement: "External rotation", primaryMuscles: ["rotatorCuff"], secondaryMuscles: ["rearDelts", "traps"], qualities: ["scapularControl", "endurance"], muscleGrade: "S", sportEmphasis: "tennis", sportGrade: "A", sportCue: "overhead shoulder-control support" },
  { name: "Cable 90/90 Internal Rotation", sourceGroup: "Cable — Sport Transfer Expansion", category: "Shoulders & posture", equipment: "Cable", movement: "Internal rotation", primaryMuscles: ["chest", "frontDelts"], secondaryMuscles: ["rotatorCuff", "lats"], qualities: ["scapularControl", "endurance"], muscleGrade: "A", sportEmphasis: "baseball", sportGrade: "A", sportCue: "arm-path and shoulder-rotation capacity" },
  { name: "Cable Serratus Punch", sourceGroup: "Cable — Sport Transfer Expansion", category: "Shoulders & posture", equipment: "Cable", movement: "Scapular protraction", primaryMuscles: ["serratusAnterior"], secondaryMuscles: ["chest", "frontDelts", "abs", "triceps"], qualities: ["scapularControl", "bracing"], muscleGrade: "A", sportEmphasis: "combat", sportGrade: "A", sportCue: "punching-path and scapular-protraction support" },
  { name: "Cable Standing Punch", sourceGroup: "Cable — Sport Transfer Expansion", category: "Chest & push", equipment: "Cable", movement: "Diagonal push", primaryMuscles: ["chest", "triceps"], secondaryMuscles: ["frontDelts", "obliques", "glutes"], qualities: ["power", "rotation", "bracing", "unilateral"], muscleGrade: "A", sportEmphasis: "combat", sportGrade: "S", sportCue: "standing punch-path force transfer" },
  { name: "Cable Incline Press-Around", sourceGroup: "Cable — Sport Transfer Expansion", category: "Chest & push", equipment: "Cable", movement: "Diagonal push", primaryMuscles: ["chest", "frontDelts"], secondaryMuscles: ["triceps", "obliques"], qualities: ["strength", "unilateral", "antiRotation"], muscleGrade: "A", sportEmphasis: "basketball", sportGrade: "A", sportCue: "diagonal finishing and torso control" },
  { name: "Cable Front-Foot-Elevated Press", sourceGroup: "Cable — Sport Transfer Expansion", category: "Chest & push", equipment: "Cable", movement: "Horizontal push", primaryMuscles: ["chest"], secondaryMuscles: ["triceps", "frontDelts", "glutes", "obliques"], qualities: ["strength", "unilateral", "bracing"], muscleGrade: "A", sportEmphasis: "combat", sportGrade: "A", sportCue: "split-stance pressing and base control" },
];

const cablePulling: CatalogInput[] = [
  { name: "Kneeling Cable Lat Pulldown", sourceGroup: "Cable — Sport Transfer Expansion", category: "Back & pull", equipment: "Cable", movement: "Vertical pull", primaryMuscles: ["lats"], secondaryMuscles: ["biceps", "upperBack", "abs"], qualities: ["strength", "bracing", "scapularControl"], muscleGrade: "S", sportEmphasis: "combat", sportGrade: "A", sportCue: "vertical pulling with organized trunk position" },
  { name: "Wide-Grip Cable Lat Pulldown", sourceGroup: "Cable — Sport Transfer Expansion", category: "Back & pull", equipment: "Cable", movement: "Vertical pull", primaryMuscles: ["lats", "upperBack"], secondaryMuscles: ["biceps", "rearDelts", "forearms"], qualities: ["strength", "scapularControl"], muscleGrade: "S", sportEmphasis: "combat", sportGrade: "A", sportCue: "wide-arm pulling and grip support" },
  { name: "Cable Straight-Arm Pulldown", sourceGroup: "Cable — Sport Transfer Expansion", category: "Back & pull", equipment: "Cable", movement: "Vertical pull", primaryMuscles: ["lats"], secondaryMuscles: ["rearDelts", "triceps", "abs"], qualities: ["strength", "bracing"], muscleGrade: "S", sportEmphasis: "combat", sportGrade: "A", sportCue: "shoulder-extension capacity for forceful pulling" },
  { name: "Cable Single-Arm Bent-Over Row", sourceGroup: "Cable — Sport Transfer Expansion", category: "Back & pull", equipment: "Cable", movement: "Horizontal pull", primaryMuscles: ["lats", "upperBack"], secondaryMuscles: ["biceps", "rearDelts", "obliques"], qualities: ["strength", "unilateral", "antiRotation"], muscleGrade: "S", sportEmphasis: "combat", sportGrade: "A", sportCue: "asymmetric pulling and trunk bracing" },
  { name: "Chest-Supported Cable Row", sourceGroup: "Cable — Sport Transfer Expansion", category: "Back & pull", equipment: "Cable", movement: "Horizontal pull", primaryMuscles: ["upperBack", "lats"], secondaryMuscles: ["biceps", "rearDelts"], qualities: ["strength", "hypertrophy", "scapularControl"], muscleGrade: "S", sportEmphasis: "baseball", sportGrade: "A", sportCue: "upper-back strength with reduced trunk fatigue" },
  { name: "Low Cable Row", sourceGroup: "Cable — Sport Transfer Expansion", category: "Back & pull", equipment: "Cable", movement: "Horizontal pull", primaryMuscles: ["lats", "upperBack"], secondaryMuscles: ["biceps", "rearDelts", "forearms"], qualities: ["strength", "hypertrophy", "scapularControl"], muscleGrade: "S", sportEmphasis: "combat", sportGrade: "A", sportCue: "low-line pulling and grip support" },
  { name: "Rope Cable Row", sourceGroup: "Cable — Sport Transfer Expansion", category: "Back & pull", equipment: "Cable", movement: "Horizontal pull", primaryMuscles: ["upperBack", "lats"], secondaryMuscles: ["biceps", "rearDelts", "forearms"], qualities: ["strength", "scapularControl", "grip"], muscleGrade: "S", sportEmphasis: "combat", sportGrade: "A", sportCue: "pulling capacity and hand-control support" },
  { name: "Cable High Row", sourceGroup: "Cable — Sport Transfer Expansion", category: "Back & pull", equipment: "Cable", movement: "Horizontal pull", primaryMuscles: ["upperBack", "rearDelts"], secondaryMuscles: ["traps", "biceps", "rotatorCuff"], qualities: ["scapularControl", "strength"], muscleGrade: "S", sportEmphasis: "baseball", sportGrade: "A", sportCue: "upper-back and shoulder-girdle control" },
  { name: "Cable Trap Raise", sourceGroup: "Cable — Sport Transfer Expansion", category: "Shoulders & posture", equipment: "Cable", movement: "Scapular elevation", primaryMuscles: ["traps"], secondaryMuscles: ["rearDelts", "rotatorCuff"], qualities: ["scapularControl", "endurance"], muscleGrade: "A", sportEmphasis: "combat", sportGrade: "B", sportCue: "neck and shoulder-girdle support" },
  { name: "Cable High Pull", sourceGroup: "Cable — Sport Transfer Expansion", category: "Shoulders & posture", equipment: "Cable", movement: "Vertical pull", primaryMuscles: ["traps", "sideDelts"], secondaryMuscles: ["glutes", "quads", "forearms"], qualities: ["power", "strength", "coordination"], muscleGrade: "A", sportEmphasis: "basketball", sportGrade: "A", sportCue: "rapid whole-body arm-drive coordination" },
  { name: "Cable Biceps Curl", sourceGroup: "Cable — Sport Transfer Expansion", category: "Arms & grip", equipment: "Cable", movement: "Elbow flexion", primaryMuscles: ["biceps"], secondaryMuscles: ["brachialis", "forearms"], qualities: ["hypertrophy", "strength", "grip"], muscleGrade: "A", sportEmphasis: "combat", sportGrade: "B", sportCue: "elbow-flexion and gripping support" },
  { name: "Rope Hammer Cable Curl", sourceGroup: "Cable — Sport Transfer Expansion", category: "Arms & grip", equipment: "Cable", movement: "Elbow flexion", primaryMuscles: ["brachialis", "forearms"], secondaryMuscles: ["biceps"], qualities: ["strength", "grip", "endurance"], muscleGrade: "A", sportEmphasis: "combat", sportGrade: "A", sportCue: "neutral-grip pulling and grip endurance" },
  { name: "Incline Cable Curl", sourceGroup: "Cable — Sport Transfer Expansion", category: "Arms & grip", equipment: "Cable", movement: "Elbow flexion", primaryMuscles: ["biceps"], secondaryMuscles: ["brachialis", "forearms"], qualities: ["hypertrophy", "strength"], muscleGrade: "A", sportEmphasis: "combat", sportGrade: "B", sportCue: "elbow-flexion strength for pulling actions" },
  { name: "High Cable Curl", sourceGroup: "Cable — Sport Transfer Expansion", category: "Arms & grip", equipment: "Cable", movement: "Elbow flexion", primaryMuscles: ["biceps"], secondaryMuscles: ["brachialis", "forearms"], qualities: ["hypertrophy", "strength"], muscleGrade: "A", sportEmphasis: "combat", sportGrade: "B", sportCue: "upper-arm pulling capacity" },
  { name: "Cable Concentration Curl", sourceGroup: "Cable — Sport Transfer Expansion", category: "Arms & grip", equipment: "Cable", movement: "Elbow flexion", primaryMuscles: ["biceps"], secondaryMuscles: ["brachialis", "forearms"], qualities: ["hypertrophy", "strength"], muscleGrade: "A", sportEmphasis: "combat", sportGrade: "B", sportCue: "controlled elbow-flexion strength" },
  { name: "Cable Spider Curl", sourceGroup: "Cable — Sport Transfer Expansion", category: "Arms & grip", equipment: "Cable", movement: "Elbow flexion", primaryMuscles: ["biceps"], secondaryMuscles: ["brachialis", "forearms"], qualities: ["hypertrophy", "strength"], muscleGrade: "A", sportEmphasis: "combat", sportGrade: "B", sportCue: "elbow-flexion capacity for pulling" },
  { name: "Cross-Body Cable Curl", sourceGroup: "Cable — Sport Transfer Expansion", category: "Arms & grip", equipment: "Cable", movement: "Elbow flexion", primaryMuscles: ["brachialis", "forearms"], secondaryMuscles: ["biceps"], qualities: ["strength", "grip", "unilateral"], muscleGrade: "A", sportEmphasis: "combat", sportGrade: "A", sportCue: "cross-body grip and elbow-flexion support" },
  { name: "Cable Triceps Pressdown", sourceGroup: "Cable — Sport Transfer Expansion", category: "Arms & grip", equipment: "Cable", movement: "Elbow extension", primaryMuscles: ["triceps"], secondaryMuscles: ["forearms", "abs"], qualities: ["strength", "hypertrophy"], muscleGrade: "A", sportEmphasis: "combat", sportGrade: "B", sportCue: "arm-lockout and pushing support" },
  { name: "Rope Cable Pressdown", sourceGroup: "Cable — Sport Transfer Expansion", category: "Arms & grip", equipment: "Cable", movement: "Elbow extension", primaryMuscles: ["triceps"], secondaryMuscles: ["forearms", "abs"], qualities: ["strength", "hypertrophy"], muscleGrade: "A", sportEmphasis: "combat", sportGrade: "B", sportCue: "elbow extension for pushing actions" },
  { name: "Reverse-Grip Cable Pressdown", sourceGroup: "Cable — Sport Transfer Expansion", category: "Arms & grip", equipment: "Cable", movement: "Elbow extension", primaryMuscles: ["triceps"], secondaryMuscles: ["forearms", "biceps"], qualities: ["strength", "hypertrophy", "grip"], muscleGrade: "A", sportEmphasis: "combat", sportGrade: "B", sportCue: "close-range arm extension and grip support" },
  { name: "Single-Arm Cable Pressdown", sourceGroup: "Cable — Sport Transfer Expansion", category: "Arms & grip", equipment: "Cable", movement: "Elbow extension", primaryMuscles: ["triceps"], secondaryMuscles: ["forearms", "abs"], qualities: ["strength", "unilateral", "bracing"], muscleGrade: "A", sportEmphasis: "combat", sportGrade: "A", sportCue: "unilateral pushing and arm-lockout capacity" },
  { name: "Cross-Body Cable Triceps Extension", sourceGroup: "Cable — Sport Transfer Expansion", category: "Arms & grip", equipment: "Cable", movement: "Elbow extension", primaryMuscles: ["triceps"], secondaryMuscles: ["chest", "frontDelts", "abs"], qualities: ["strength", "unilateral", "bracing"], muscleGrade: "A", sportEmphasis: "combat", sportGrade: "A", sportCue: "cross-body extension and bracing" },
  { name: "Cable Triceps Kickback", sourceGroup: "Cable — Sport Transfer Expansion", category: "Arms & grip", equipment: "Cable", movement: "Elbow extension", primaryMuscles: ["triceps"], secondaryMuscles: ["rearDelts", "forearms"], qualities: ["hypertrophy", "endurance"], muscleGrade: "A", sportEmphasis: "baseball", sportGrade: "B", sportCue: "posterior arm endurance" },
  { name: "Cable Overhead Triceps Extension", sourceGroup: "Cable — Sport Transfer Expansion", category: "Arms & grip", equipment: "Cable", movement: "Elbow extension", primaryMuscles: ["triceps"], secondaryMuscles: ["frontDelts", "abs"], qualities: ["strength", "hypertrophy", "overhead"], muscleGrade: "A", sportEmphasis: "baseball", sportGrade: "A", sportCue: "overhead elbow-extension capacity" },
  { name: "Cable Wrist Extension", sourceGroup: "Cable — Sport Transfer Expansion", category: "Arms & grip", equipment: "Cable", movement: "Wrist extension", primaryMuscles: ["forearms"], secondaryMuscles: ["biceps"], qualities: ["grip", "endurance"], muscleGrade: "A", sportEmphasis: "tennis", sportGrade: "A", sportCue: "forearm and racket-control support" },
];

const cableLowerAndCore: CatalogInput[] = [
  { name: "Cable Belt Squat", sourceGroup: "Cable — Sport Transfer Expansion", category: "Lower body", equipment: "Cable", movement: "Squat", primaryMuscles: ["quads", "glutes"], secondaryMuscles: ["adductors", "hamstrings", "abs"], qualities: ["strength", "hypertrophy"], muscleGrade: "S", sportEmphasis: "basketball", sportGrade: "A", sportCue: "leg-drive support with reduced upper-body loading" },
  { name: "Cable Goblet Squat", sourceGroup: "Cable — Sport Transfer Expansion", category: "Lower body", equipment: "Cable", movement: "Squat", primaryMuscles: ["quads", "glutes"], secondaryMuscles: ["adductors", "abs"], qualities: ["strength", "bracing", "mobility"], muscleGrade: "S", sportEmphasis: "soccer", sportGrade: "A", sportCue: "knee and hip extension for field positions" },
  { name: "Cable Front Squat", sourceGroup: "Cable — Sport Transfer Expansion", category: "Lower body", equipment: "Cable", movement: "Squat", primaryMuscles: ["quads", "glutes"], secondaryMuscles: ["adductors", "abs", "upperBack"], qualities: ["strength", "bracing"], muscleGrade: "S", sportEmphasis: "basketball", sportGrade: "A", sportCue: "upright leg-drive and contact-position support" },
  { name: "Cable Deadlift", sourceGroup: "Cable — Sport Transfer Expansion", category: "Lower body", equipment: "Cable", movement: "Hinge", primaryMuscles: ["glutes", "hamstrings"], secondaryMuscles: ["quads", "lowerBack", "abs"], qualities: ["strength", "bracing"], muscleGrade: "S", sportEmphasis: "soccer", sportGrade: "A", sportCue: "posterior-chain force for acceleration support" },
  { name: "Cable Good Morning", sourceGroup: "Cable — Sport Transfer Expansion", category: "Lower body", equipment: "Cable", movement: "Hinge", primaryMuscles: ["hamstrings", "glutes"], secondaryMuscles: ["lowerBack", "abs"], qualities: ["strength", "hypertrophy", "bracing"], muscleGrade: "S", sportEmphasis: "soccer", sportGrade: "A", sportCue: "hinge control and posterior-chain capacity" },
  { name: "Cable Single-Leg Deadlift", sourceGroup: "Cable — Sport Transfer Expansion", category: "Lower body", equipment: "Cable", movement: "Single-leg hinge", primaryMuscles: ["hamstrings", "glutes"], secondaryMuscles: ["abductors", "adductors", "abs"], qualities: ["unilateral", "bracing", "balance", "strength"], muscleGrade: "S", sportEmphasis: "soccer", sportGrade: "A", sportCue: "single-leg hinge and field-balance support" },
  { name: "Cable Step-Up", sourceGroup: "Cable — Sport Transfer Expansion", category: "Lower body", equipment: "Cable", movement: "Single-leg squat", primaryMuscles: ["quads", "glutes"], secondaryMuscles: ["calves", "abductors", "abs"], qualities: ["unilateral", "strength", "balance"], muscleGrade: "S", sportEmphasis: "basketball", sportGrade: "A", sportCue: "single-leg drive and landing support" },
  { name: "Cable Lateral Step-Up", sourceGroup: "Cable — Sport Transfer Expansion", category: "Lower body", equipment: "Cable", movement: "Lateral single-leg squat", primaryMuscles: ["quads", "glutes", "abductors"], secondaryMuscles: ["adductors", "calves", "abs"], qualities: ["unilateral", "lateralControl", "strength"], muscleGrade: "S", sportEmphasis: "basketball", sportGrade: "A", sportCue: "lateral leg drive and court-control support" },
  { name: "Cable Skater Squat", sourceGroup: "Cable — Sport Transfer Expansion", category: "Lower body", equipment: "Cable", movement: "Single-leg squat", primaryMuscles: ["quads", "glutes"], secondaryMuscles: ["abductors", "adductors", "abs"], qualities: ["unilateral", "balance", "strength"], muscleGrade: "S", sportEmphasis: "soccer", sportGrade: "A", sportCue: "single-leg control for cutting support" },
  { name: "Cable Hip Thrust", sourceGroup: "Cable — Sport Transfer Expansion", category: "Lower body", equipment: "Cable", movement: "Hip extension", primaryMuscles: ["glutes"], secondaryMuscles: ["hamstrings", "adductors", "abs"], qualities: ["strength", "hypertrophy", "sprintSupport"], muscleGrade: "S", sportEmphasis: "soccer", sportGrade: "A", sportCue: "hip-extension capacity for acceleration support" },
  { name: "Cable Quadruped Hip Extension", sourceGroup: "Cable — Sport Transfer Expansion", category: "Lower body", equipment: "Cable", movement: "Hip extension", primaryMuscles: ["glutes"], secondaryMuscles: ["hamstrings", "abs"], qualities: ["unilateral", "strength", "balance"], muscleGrade: "A", sportEmphasis: "soccer", sportGrade: "B", sportCue: "single-leg hip-extension support" },
  { name: "Cable Donkey Kick", sourceGroup: "Cable — Sport Transfer Expansion", category: "Lower body", equipment: "Cable", movement: "Hip extension", primaryMuscles: ["glutes"], secondaryMuscles: ["hamstrings", "abs"], qualities: ["unilateral", "strength"], muscleGrade: "A", sportEmphasis: "soccer", sportGrade: "B", sportCue: "controlled hip-drive support" },
  { name: "Cable Fire Hydrant", sourceGroup: "Cable — Sport Transfer Expansion", category: "Lower body", equipment: "Cable", movement: "Hip abduction", primaryMuscles: ["abductors"], secondaryMuscles: ["glutes", "abs"], qualities: ["unilateral", "lateralControl", "balance"], muscleGrade: "A", sportEmphasis: "soccer", sportGrade: "A", sportCue: "lateral hip-control support" },
  { name: "Cable Standing Hip Adduction", sourceGroup: "Cable — Sport Transfer Expansion", category: "Lower body", equipment: "Cable", movement: "Hip adduction", primaryMuscles: ["adductors"], secondaryMuscles: ["glutes", "abs"], qualities: ["unilateral", "lateralControl", "balance"], muscleGrade: "A", sportEmphasis: "soccer", sportGrade: "A", sportCue: "medial hip and cutting-control support" },
  { name: "Cable Standing Hip Abduction", sourceGroup: "Cable — Sport Transfer Expansion", category: "Lower body", equipment: "Cable", movement: "Hip abduction", primaryMuscles: ["abductors"], secondaryMuscles: ["glutes", "abs"], qualities: ["unilateral", "lateralControl", "balance"], muscleGrade: "A", sportEmphasis: "soccer", sportGrade: "A", sportCue: "pelvic-control and lateral-support capacity" },
  { name: "Cable Hamstring Curl", sourceGroup: "Cable — Sport Transfer Expansion", category: "Lower body", equipment: "Cable", movement: "Knee flexion", primaryMuscles: ["hamstrings"], secondaryMuscles: ["calves", "glutes"], qualities: ["strength", "hypertrophy", "eccentric"], muscleGrade: "S", sportEmphasis: "soccer", sportGrade: "A", sportCue: "knee-flexor capacity for running support" },
  { name: "Cable Standing Leg Curl", sourceGroup: "Cable — Sport Transfer Expansion", category: "Lower body", equipment: "Cable", movement: "Knee flexion", primaryMuscles: ["hamstrings"], secondaryMuscles: ["calves", "glutes", "abs"], qualities: ["unilateral", "strength", "balance"], muscleGrade: "S", sportEmphasis: "soccer", sportGrade: "A", sportCue: "single-leg knee-flexion support" },
  { name: "Cable Leg Extension", sourceGroup: "Cable — Sport Transfer Expansion", category: "Lower body", equipment: "Cable", movement: "Knee extension", primaryMuscles: ["quads"], secondaryMuscles: ["abs"], qualities: ["strength", "hypertrophy"], muscleGrade: "S", sportEmphasis: "basketball", sportGrade: "B", sportCue: "knee-extension capacity for jumping support" },
  { name: "Cable Calf Raise", sourceGroup: "Cable — Sport Transfer Expansion", category: "Lower body", equipment: "Cable", movement: "Plantar flexion", primaryMuscles: ["calves"], secondaryMuscles: ["tibialis", "abs"], qualities: ["strength", "elasticity", "endurance"], muscleGrade: "A", sportEmphasis: "soccer", sportGrade: "A", sportCue: "ankle drive and repeated-running support" },
  { name: "Cable Tibialis Raise", sourceGroup: "Cable — Sport Transfer Expansion", category: "Lower body", equipment: "Cable", movement: "Dorsiflexion", primaryMuscles: ["tibialis"], secondaryMuscles: ["calves"], qualities: ["strength", "endurance"], muscleGrade: "A", sportEmphasis: "soccer", sportGrade: "B", sportCue: "ankle-control support during running" },
  { name: "Cable Reverse Lunge", sourceGroup: "Cable — Sport Transfer Expansion", category: "Lower body", equipment: "Cable", movement: "Single-leg squat", primaryMuscles: ["quads", "glutes"], secondaryMuscles: ["hamstrings", "adductors", "abductors", "abs"], qualities: ["unilateral", "deceleration", "strength"], muscleGrade: "S", sportEmphasis: "soccer", sportGrade: "A", sportCue: "braking and re-acceleration support" },
  { name: "Cable Lateral Lunge", sourceGroup: "Cable — Sport Transfer Expansion", category: "Lower body", equipment: "Cable", movement: "Lateral lunge", primaryMuscles: ["quads", "glutes", "adductors"], secondaryMuscles: ["abductors", "hamstrings", "abs"], qualities: ["unilateral", "lateralControl", "deceleration"], muscleGrade: "S", sportEmphasis: "tennis", sportGrade: "A", sportCue: "lateral court movement and braking support" },
  { name: "Cable Crossover Step Lunge", sourceGroup: "Cable — Sport Transfer Expansion", category: "Lower body", equipment: "Cable", movement: "Diagonal lunge", primaryMuscles: ["glutes", "quads", "adductors"], secondaryMuscles: ["abductors", "obliques", "abs"], qualities: ["unilateral", "lateralControl", "rotation"], muscleGrade: "S", sportEmphasis: "tennis", sportGrade: "A", sportCue: "diagonal step and rotational-base support" },
  { name: "Cable Forward March", sourceGroup: "Cable — Sport Transfer Expansion", category: "Lower body", equipment: "Cable", movement: "Resisted gait", primaryMuscles: ["glutes", "quads", "calves"], secondaryMuscles: ["abs", "hipFlexors"], qualities: ["sprintSupport", "conditioning", "bracing"], muscleGrade: "S", sportEmphasis: "soccer", sportGrade: "A", sportCue: "forward drive and gait-control support" },
  { name: "Cable Standing Knee Drive", sourceGroup: "Cable — Sport Transfer Expansion", category: "Lower body", equipment: "Cable", movement: "Hip flexion", primaryMuscles: ["hipFlexors", "quads"], secondaryMuscles: ["abs", "glutes", "abductors"], qualities: ["unilateral", "sprintSupport", "balance"], muscleGrade: "A", sportEmphasis: "soccer", sportGrade: "A", sportCue: "knee-drive and stance-control support" },
  { name: "Cable Dead Bug", sourceGroup: "Cable — Sport Transfer Expansion", category: "Core & rotation", equipment: "Cable", movement: "Anti-extension", primaryMuscles: ["abs", "obliques"], secondaryMuscles: ["glutes", "hipFlexors"], qualities: ["bracing", "antiRotation", "coordination"], muscleGrade: "S", sportEmphasis: "combat", sportGrade: "A", sportCue: "trunk-position control under limb movement" },
  { name: "Cable Reverse Chop", sourceGroup: "Cable — Sport Transfer Expansion", category: "Core & rotation", equipment: "Cable", movement: "Rotation", primaryMuscles: ["obliques", "abs"], secondaryMuscles: ["glutes", "lats", "frontDelts"], qualities: ["rotation", "power", "bracing"], muscleGrade: "S", sportEmphasis: "tennis", sportGrade: "A", sportCue: "upward diagonal trunk-to-arm force transfer" },
  { name: "Cable Horizontal Chop", sourceGroup: "Cable — Sport Transfer Expansion", category: "Core & rotation", equipment: "Cable", movement: "Rotation", primaryMuscles: ["obliques", "abs"], secondaryMuscles: ["glutes", "chest", "lats"], qualities: ["rotation", "power", "bracing"], muscleGrade: "S", sportEmphasis: "baseball", sportGrade: "A", sportCue: "horizontal rotational force-transfer support" },
  { name: "Cable Rotational Row", sourceGroup: "Cable — Sport Transfer Expansion", category: "Core & rotation", equipment: "Cable", movement: "Rotation", primaryMuscles: ["lats", "upperBack", "obliques"], secondaryMuscles: ["biceps", "glutes", "forearms"], qualities: ["rotation", "unilateral", "bracing", "grip"], muscleGrade: "S", sportEmphasis: "combat", sportGrade: "A", sportCue: "rotational pulling and grip support" },
  { name: "Cable Anti-Rotation Walkout", sourceGroup: "Cable — Sport Transfer Expansion", category: "Core & rotation", equipment: "Cable", movement: "Anti-rotation", primaryMuscles: ["obliques", "abs"], secondaryMuscles: ["glutes", "abductors", "triceps"], qualities: ["antiRotation", "bracing", "unilateral"], muscleGrade: "S", sportEmphasis: "combat", sportGrade: "A", sportCue: "upright anti-rotation and stance control" },
];

const athleticAlternatives: CatalogInput[] = [
  { name: "Alternating Landmine Press", sourceGroup: "Athletic — Sport Transfer Expansion", category: "Power & athletic", equipment: "Landmine", movement: "Diagonal push", primaryMuscles: ["frontDelts", "chest"], secondaryMuscles: ["triceps", "obliques", "glutes"], qualities: ["strength", "unilateral", "rotation", "bracing"], muscleGrade: "A", sportEmphasis: "combat", sportGrade: "A", sportCue: "alternating press rhythm and force transfer" },
  { name: "Tall-Kneeling Landmine Press", sourceGroup: "Athletic — Sport Transfer Expansion", category: "Power & athletic", equipment: "Landmine", movement: "Diagonal push", primaryMuscles: ["frontDelts", "chest"], secondaryMuscles: ["triceps", "abs", "glutes"], qualities: ["strength", "bracing", "antiRotation"], muscleGrade: "A", sportEmphasis: "baseball", sportGrade: "A", sportCue: "upright trunk and shoulder-force control" },
  { name: "Chest-Supported Landmine Row", sourceGroup: "Athletic — Sport Transfer Expansion", category: "Back & pull", equipment: "Landmine", movement: "Horizontal pull", primaryMuscles: ["lats", "upperBack"], secondaryMuscles: ["biceps", "rearDelts", "forearms"], qualities: ["strength", "grip", "scapularControl"], muscleGrade: "S", sportEmphasis: "combat", sportGrade: "A", sportCue: "strong pulling with controlled trunk demand" },
  { name: "Offset Landmine Row", sourceGroup: "Athletic — Sport Transfer Expansion", category: "Back & pull", equipment: "Landmine", movement: "Horizontal pull", primaryMuscles: ["lats", "upperBack"], secondaryMuscles: ["biceps", "obliques", "forearms"], qualities: ["strength", "unilateral", "antiRotation", "grip"], muscleGrade: "S", sportEmphasis: "combat", sportGrade: "A", sportCue: "asymmetric pulling and torso-stiffness support" },
  { name: "Landmine Full Contact Twist", sourceGroup: "Athletic — Sport Transfer Expansion", category: "Core & rotation", equipment: "Landmine", movement: "Rotation", primaryMuscles: ["obliques", "glutes"], secondaryMuscles: ["abs", "frontDelts", "quads"], qualities: ["rotation", "power", "bracing"], muscleGrade: "S", sportEmphasis: "tennis", sportGrade: "A", sportCue: "whole-body rotational force sequencing" },
  { name: "Landmine Split Press", sourceGroup: "Athletic — Sport Transfer Expansion", category: "Power & athletic", equipment: "Landmine", movement: "Diagonal push", primaryMuscles: ["frontDelts", "triceps"], secondaryMuscles: ["chest", "quads", "glutes", "abs"], qualities: ["strength", "unilateral", "bracing"], muscleGrade: "A", sportEmphasis: "basketball", sportGrade: "A", sportCue: "split-stance upward force application" },
  { name: "Kettlebell Clean", sourceGroup: "Athletic — Sport Transfer Expansion", category: "Power & athletic", equipment: "Kettlebell", movement: "Explosive hinge", primaryMuscles: ["glutes", "hamstrings", "traps"], secondaryMuscles: ["quads", "forearms", "abs"], qualities: ["power", "sprintSupport", "grip", "bracing"], muscleGrade: "S", sportEmphasis: "combat", sportGrade: "A", sportCue: "hip-drive and grip coordination" },
  { name: "Kettlebell Snatch", sourceGroup: "Athletic — Sport Transfer Expansion", category: "Power & athletic", equipment: "Kettlebell", movement: "Explosive hinge", primaryMuscles: ["glutes", "hamstrings", "traps"], secondaryMuscles: ["frontDelts", "forearms", "abs"], qualities: ["power", "sprintSupport", "grip", "overhead"], muscleGrade: "S", sportEmphasis: "baseball", sportGrade: "A", sportCue: "explosive hip-to-overhead coordination" },
  { name: "Kettlebell Clean and Press", sourceGroup: "Athletic — Sport Transfer Expansion", category: "Power & athletic", equipment: "Kettlebell", movement: "Explosive push", primaryMuscles: ["glutes", "frontDelts", "triceps"], secondaryMuscles: ["quads", "traps", "forearms", "abs"], qualities: ["power", "strength", "grip", "bracing"], muscleGrade: "S", sportEmphasis: "combat", sportGrade: "A", sportCue: "whole-body force transfer and grip support" },
  { name: "Turkish Get-Up", sourceGroup: "Athletic — Sport Transfer Expansion", category: "Power & athletic", equipment: "Kettlebell", movement: "Loaded transition", primaryMuscles: ["frontDelts", "abs", "glutes"], secondaryMuscles: ["triceps", "obliques", "quads", "forearms"], qualities: ["stability", "bracing", "unilateral", "coordination"], muscleGrade: "S", sportEmphasis: "combat", sportGrade: "A", sportCue: "ground-to-standing control and shoulder stability" },
  { name: "Lateral Goblet Squat", sourceGroup: "Athletic — Sport Transfer Expansion", category: "Lower body", equipment: "Kettlebell", movement: "Lateral squat", primaryMuscles: ["quads", "glutes", "adductors"], secondaryMuscles: ["abductors", "hamstrings", "abs"], qualities: ["lateralControl", "strength", "mobility"], muscleGrade: "S", sportEmphasis: "tennis", sportGrade: "A", sportCue: "frontal-plane strength and court-control support" },
  { name: "Skater Bound", sourceGroup: "Athletic — Sport Transfer Expansion", category: "Power & athletic", equipment: "Bodyweight", movement: "Lateral jump", primaryMuscles: ["glutes", "quads", "abductors"], secondaryMuscles: ["adductors", "calves", "abs"], qualities: ["power", "lateralControl", "deceleration", "unilateral"], muscleGrade: "S", sportEmphasis: "basketball", sportGrade: "A", sportCue: "lateral propulsion and landing control" },
  { name: "Single-Leg Box Jump", sourceGroup: "Athletic — Sport Transfer Expansion", category: "Power & athletic", equipment: "Plyometric box", movement: "Single-leg jump", primaryMuscles: ["quads", "glutes", "calves"], secondaryMuscles: ["hamstrings", "abductors", "abs"], qualities: ["power", "jumping", "unilateral", "elasticity"], muscleGrade: "S", sportEmphasis: "basketball", sportGrade: "A", sportCue: "single-leg takeoff and landing support" },
  { name: "Depth Drop to Stick", sourceGroup: "Athletic — Sport Transfer Expansion", category: "Power & athletic", equipment: "Plyometric box", movement: "Landing", primaryMuscles: ["quads", "glutes"], secondaryMuscles: ["hamstrings", "calves", "abductors", "abs"], qualities: ["deceleration", "unilateral", "bracing"], muscleGrade: "S", sportEmphasis: "basketball", sportGrade: "A", sportCue: "landing and force-absorption control" },
  { name: "Drop Landing", sourceGroup: "Athletic — Sport Transfer Expansion", category: "Power & athletic", equipment: "Plyometric box", movement: "Landing", primaryMuscles: ["quads", "glutes"], secondaryMuscles: ["hamstrings", "calves", "abductors", "abs"], qualities: ["deceleration", "bracing", "coordination"], muscleGrade: "S", sportEmphasis: "basketball", sportGrade: "A", sportCue: "bilateral landing and position-control support" },
  { name: "Assisted Nordic Hamstring Curl", sourceGroup: "Athletic — Sport Transfer Expansion", category: "Lower body", equipment: "Bodyweight", movement: "Knee flexion", primaryMuscles: ["hamstrings"], secondaryMuscles: ["glutes", "calves", "abs"], qualities: ["strength", "eccentric", "unilateral"], muscleGrade: "S", sportEmphasis: "soccer", sportGrade: "A", sportCue: "eccentric knee-flexor capacity for running support" },
  { name: "Side Plank Hip Adduction", sourceGroup: "Athletic — Sport Transfer Expansion", category: "Core & rotation", equipment: "Bodyweight", movement: "Hip adduction", primaryMuscles: ["adductors", "obliques"], secondaryMuscles: ["abs", "abductors"], qualities: ["bracing", "lateralControl", "unilateral"], muscleGrade: "S", sportEmphasis: "soccer", sportGrade: "A", sportCue: "groin and lateral-trunk control support" },
  { name: "Sled March", sourceGroup: "Athletic — Sport Transfer Expansion", category: "Power & athletic", equipment: "Sled", movement: "Resisted gait", primaryMuscles: ["quads", "glutes", "calves"], secondaryMuscles: ["hamstrings", "abs", "frontDelts"], qualities: ["sprintSupport", "conditioning", "bracing"], muscleGrade: "S", sportEmphasis: "soccer", sportGrade: "A", sportCue: "forward-drive and acceleration support" },
  { name: "Battle Rope Slams", sourceGroup: "Athletic — Sport Transfer Expansion", category: "Power & athletic", equipment: "Battle ropes", movement: "Overhead slam", primaryMuscles: ["lats", "triceps", "abs"], secondaryMuscles: ["frontDelts", "glutes", "quads", "forearms"], qualities: ["power", "conditioning", "bracing", "grip"], muscleGrade: "A", sportEmphasis: "combat", sportGrade: "A", sportCue: "upper-body power endurance and grip support" },
  { name: "Battle Rope Alternating Waves", sourceGroup: "Athletic — Sport Transfer Expansion", category: "Power & athletic", equipment: "Battle ropes", movement: "Alternating arm drive", primaryMuscles: ["frontDelts", "forearms", "abs"], secondaryMuscles: ["triceps", "lats", "glutes"], qualities: ["conditioning", "grip", "bracing", "endurance"], muscleGrade: "A", sportEmphasis: "combat", sportGrade: "A", sportCue: "repeatable arm drive and trunk-bracing support" },
];

export const expandedExercises: Exercise[] = [...cablePressing, ...cablePulling, ...cableLowerAndCore, ...athleticAlternatives].map((exercise, index) => ({
  id: 301 + index,
  name: exercise.name,
  sourceGroup: exercise.sourceGroup,
  category: exercise.category,
  equipment: exercise.equipment,
  movement: exercise.movement,
  primaryMuscles: exercise.primaryMuscles,
  secondaryMuscles: exercise.secondaryMuscles,
  qualities: exercise.qualities,
  muscleGrade: exercise.muscleGrade,
  sportFit: sportFit(exercise),
}));
