/** Kinetic Field Manual: user-supplied sport movements, retained verbatim as the source scope for research. */

export interface SportMovementSource {
  id: string;
  label: string;
  movements: string[];
}

export const sportMovementSource: SportMovementSource[] = [
  {
    "id": "wrestling",
    "label": "Wrestling",
    "movements": [
      "penetration step",
      "double-leg shot",
      "single-leg shot",
      "high-crotch entry",
      "sprawl",
      "reshot",
      "stand-up escape",
      "hip-heist",
      "sit-out",
      "switch",
      "mat return",
      "body-lock lift",
      "underhook drive",
      "overhook/whizzer",
      "snapdown",
      "front-headlock pull",
      "hand fighting",
      "lateral shuffle",
      "bridge",
      "rotational finish"
    ]
  },
  {
    "id": "american-football",
    "label": "American football",
    "movements": [
      "acceleration sprint",
      "max-velocity sprint",
      "backpedal",
      "lateral shuffle",
      "crossover run",
      "three-point-stance start",
      "blocking drive",
      "pass-rush bull rush",
      "pass-rush bend",
      "tackling drive",
      "cutting",
      "deceleration",
      "route break",
      "vertical jump",
      "stiff-arm",
      "throwing",
      "catching overhead",
      "hip turn",
      "change of direction",
      "ball-carrying contact absorption"
    ]
  },
  {
    "id": "basketball",
    "label": "Basketball",
    "movements": [
      "acceleration",
      "defensive shuffle",
      "crossover step",
      "hard deceleration",
      "cutting",
      "jump shot",
      "layup takeoff",
      "dunk takeoff",
      "rebounding jump",
      "box-out",
      "crossover dribble",
      "drive initiation",
      "drop step",
      "pivot",
      "closeout",
      "backpedal",
      "screen contact",
      "overhead pass",
      "chest pass",
      "lateral recovery"
    ]
  },
  {
    "id": "soccer",
    "label": "Soccer",
    "movements": [
      "acceleration",
      "max-speed sprinting",
      "cutting",
      "lateral shuffle",
      "deceleration",
      "instep kick",
      "driven pass",
      "long pass",
      "crossing",
      "shooting",
      "jumping header",
      "standing header",
      "tackling",
      "shielding",
      "jockeying",
      "backpedaling",
      "hip turn",
      "single-leg landing",
      "goalkeeper dive",
      "throw-in"
    ]
  },
  {
    "id": "baseball",
    "label": "Baseball",
    "movements": [
      "batting rotation",
      "pitching acceleration",
      "pitching deceleration",
      "overhand throwing",
      "fielding ground balls",
      "lateral fielding shuffle",
      "sprinting from the plate",
      "base stealing start",
      "rounding bases",
      "sliding",
      "diving catch",
      "vertical jump catch",
      "crow hop",
      "catcher squat",
      "catcher throw",
      "first-base stretch",
      "rotational transfer",
      "single-leg pitching balance",
      "scapular retraction",
      "trunk anti-rotation"
    ]
  },
  {
    "id": "track-and-field",
    "label": "Track & field",
    "movements": [
      "block start",
      "acceleration",
      "upright sprinting",
      "maximal-velocity sprinting",
      "sprint deceleration",
      "hurdle takeoff",
      "hurdle clearance",
      "long-jump takeoff",
      "triple-jump bound",
      "high-jump takeoff",
      "pole-vault plant",
      "shot-put drive",
      "shot-put release",
      "discus rotation",
      "hammer rotation",
      "javelin approach",
      "javelin throw",
      "distance-running stride",
      "race-walking stride",
      "steeplechase barrier clearance"
    ]
  },
  {
    "id": "swimming",
    "label": "Swimming",
    "movements": [
      "freestyle pull",
      "freestyle catch",
      "freestyle kick",
      "freestyle body rotation",
      "backstroke pull",
      "backstroke kick",
      "breaststroke pull",
      "breaststroke kick",
      "butterfly pull",
      "dolphin kick",
      "streamline",
      "wall push-off",
      "flip turn",
      "open turn",
      "diving start",
      "underwater dolphin",
      "breathing rotation",
      "scapular protraction",
      "shoulder internal rotation",
      "finishing reach"
    ]
  },
  {
    "id": "tennis",
    "label": "Tennis",
    "movements": [
      "forehand",
      "backhand",
      "serve",
      "overhead smash",
      "volley",
      "backhand volley",
      "slice",
      "topspin drive",
      "lateral shuffle",
      "split step",
      "crossover recovery",
      "forward acceleration",
      "deceleration",
      "open-stance rotation",
      "closed-stance drive",
      "serve leg drive",
      "jumping forehand",
      "drop-shot reach",
      "wide-ball lunge",
      "rotational recovery"
    ]
  },
  {
    "id": "volleyball",
    "label": "Volleyball",
    "movements": [
      "approach jump",
      "vertical block jump",
      "spike",
      "overhead serve",
      "jump serve",
      "forearm pass",
      "overhead set",
      "lateral blocking shuffle",
      "crossover block step",
      "dive",
      "roll recovery",
      "low defensive stance",
      "single-leg takeoff",
      "bilateral takeoff",
      "landing",
      "overhead reach",
      "shoulder swing",
      "trunk rotation",
      "quick acceleration",
      "backward defensive movement"
    ]
  },
  {
    "id": "boxing",
    "label": "Boxing",
    "movements": [
      "jab",
      "cross",
      "lead hook",
      "rear hook",
      "uppercut",
      "overhand",
      "body shot",
      "slip",
      "roll",
      "pull-back",
      "parry",
      "high guard",
      "lateral step",
      "pivot",
      "forward step",
      "backward step",
      "rotational punch drive",
      "level change",
      "clinch control",
      "explosive combination punching"
    ]
  },
  {
    "id": "mma",
    "label": "MMA",
    "movements": [
      "jab",
      "cross",
      "hook",
      "roundhouse kick",
      "front kick",
      "knee strike",
      "elbow strike",
      "double-leg takedown",
      "single-leg takedown",
      "sprawl",
      "body-lock takedown",
      "hip throw",
      "technical stand-up",
      "guard retention",
      "bridge-and-shrimp escape",
      "ground-and-pound",
      "clinch pummeling",
      "cage wrestling drive",
      "submission squeeze",
      "scramble"
    ]
  },
  {
    "id": "brazilian-jiu-jitsu",
    "label": "Brazilian jiu-jitsu",
    "movements": [
      "shrimp",
      "bridge",
      "technical stand-up",
      "guard retention",
      "closed-guard squeeze",
      "hip escape",
      "armbar hip extension",
      "triangle squeeze",
      "rear-naked-choke squeeze",
      "guillotine squeeze",
      "hip-bump sweep",
      "scissor sweep",
      "wrestling stand-up",
      "guard pass drive",
      "knee-cut pass",
      "body-lock pass",
      "mount stabilization",
      "back-control hooks",
      "grip fighting",
      "inversion"
    ]
  },
  {
    "id": "ice-hockey",
    "label": "Ice hockey",
    "movements": [
      "skating acceleration",
      "forward stride",
      "backward skating",
      "crossover",
      "backward crossover",
      "hard stop",
      "directional cut",
      "slapshot",
      "wrist shot",
      "snap shot",
      "one-timer",
      "stick handling",
      "poke check",
      "body check",
      "board battle",
      "faceoff pull",
      "low skating stance",
      "lateral goalie push",
      "goalie butterfly",
      "explosive crease recovery"
    ]
  },
  {
    "id": "lacrosse",
    "label": "Lacrosse",
    "movements": [
      "overhand shot",
      "sidearm shot",
      "underhand shot",
      "passing",
      "catching",
      "cradling",
      "dodging",
      "split dodge",
      "roll dodge",
      "faceoff clamp",
      "ground-ball scoop",
      "sprinting",
      "lateral defensive shuffle",
      "backpedal",
      "checking",
      "body positioning",
      "rotational shooting",
      "overhead checking",
      "jumping shot",
      "rapid deceleration"
    ]
  },
  {
    "id": "rugby",
    "label": "Rugby",
    "movements": [
      "acceleration",
      "maximal sprinting",
      "lateral cutting",
      "sidestep",
      "tackling",
      "tackle absorption",
      "rucking drive",
      "mauling drive",
      "scrum push",
      "lineout jump",
      "lineout lift",
      "stiff-arm",
      "passing",
      "rotational pass",
      "kicking",
      "jumping catch",
      "ground-to-feet recovery",
      "ball-carrying drive",
      "backward defensive movement",
      "change of direction"
    ]
  },
  {
    "id": "golf",
    "label": "Golf",
    "movements": [
      "backswing rotation",
      "downswing rotation",
      "hip initiation",
      "shoulder rotation",
      "weight shift",
      "lead-leg bracing",
      "trail-leg drive",
      "trunk anti-extension",
      "trunk anti-rotation",
      "wrist hinge",
      "wrist release",
      "scapular retraction",
      "shoulder adduction",
      "driving swing",
      "iron swing",
      "pitching motion",
      "bunker swing",
      "putting stroke",
      "rotational deceleration",
      "single-leg stabilization"
    ]
  },
  {
    "id": "gymnastics",
    "label": "Gymnastics",
    "movements": [
      "handstand",
      "handstand push",
      "planche",
      "front lever",
      "back lever",
      "muscle-up",
      "ring dip",
      "iron cross",
      "L-sit",
      "V-sit",
      "hollow-body hold",
      "arch-body hold",
      "rope climb",
      "pull-up",
      "press-to-handstand",
      "tumbling takeoff",
      "backflip",
      "front flip",
      "vault takeoff",
      "landing stabilization"
    ]
  },
  {
    "id": "rowing",
    "label": "Rowing",
    "movements": [
      "catch position",
      "leg drive",
      "hip swing",
      "arm pull",
      "finish position",
      "recovery",
      "scapular retraction",
      "shoulder extension",
      "knee extension",
      "hip extension",
      "ankle plantarflexion",
      "trunk bracing",
      "trunk hinge",
      "grip endurance",
      "repeated pulling",
      "explosive start stroke",
      "high-rate stroke",
      "power stroke",
      "sustained stroke cycle",
      "stroke deceleration"
    ]
  },
  {
    "id": "skiing",
    "label": "Skiing",
    "movements": [
      "downhill squat stance",
      "carving turn",
      "edge transition",
      "lateral weight shift",
      "hip angulation",
      "knee flexion absorption",
      "mogul absorption",
      "jump takeoff",
      "landing",
      "rotational aerial control",
      "pole plant",
      "skating stride",
      "cross-country push-off",
      "double-pole drive",
      "uphill stride",
      "downhill stabilization",
      "rapid direction change",
      "eccentric braking",
      "single-leg stabilization",
      "trunk anti-rotation"
    ]
  },
  {
    "id": "olympic-weightlifting",
    "label": "Olympic weightlifting",
    "movements": [
      "first pull",
      "second pull",
      "triple extension",
      "clean pull",
      "snatch pull",
      "power clean",
      "squat clean",
      "power snatch",
      "squat snatch",
      "clean catch",
      "snatch catch",
      "front-squat recovery",
      "overhead-squat stabilization",
      "split jerk",
      "power jerk",
      "push jerk",
      "jerk dip",
      "jerk drive",
      "split-stance stabilization",
      "overhead lockout"
    ]
  }
] as const;
