import type { StrengthReferenceCandidate } from "./strengthReferenceQualification";

type AuditGateSpec = Pick<StrengthReferenceCandidate, "id" | "label" | "citationUrl" | "referencePopulation" | "scope" | "boundary"> & {
  extraFields?: readonly string[];
  sourceAccess?: StrengthReferenceCandidate["sourceAccess"];
  expectedSport?: string;
};

const sourceSpecificGate = (spec: AuditGateSpec): StrengthReferenceCandidate => ({
  ...spec,
  requiredFields: ["exerciseName", "testType", "sex", "ageYears", "sourcePopulationId", "sourceProtocolId", ...(spec.extraFields ?? [])],
  sourcePopulationId: `${spec.id}:population`,
  sourceProtocolId: `${spec.id}:protocol`,
  sourceTestId: `${spec.id}:exact-test`,
  sourceNormalizationId: `${spec.id}:normalization`,
  sourceAccess: spec.sourceAccess ?? "authorized_not_ingested",
  expectedSport: spec.expectedSport,
  numericReferenceStatus: "not_ingested",
});

/**
 * One entry per separately qualified audit source. These are eligibility
 * descriptions—not imported percentiles. A future numeric data import has to
 * match this ID, its population key, its protocol key, and a reviewed license.
 */
export const auditedStrengthReferenceGates: readonly StrengthReferenceCandidate[] = ([
  { id: "campos_2026_elite_judo", label: "Elite judo 1RM reference", citationUrl: "https://pubmed.ncbi.nlm.nih.gov/41996598/", referencePopulation: "National- and international-level elite judo athletes.", scope: "1RM back squat, bench press, and prone row only.", extraFields: ["bodyMassKgAtTest", "competitiveLevel", "weightCategory", "sport"], sourceAccess: "license_review_required", expectedSport: "judo", boundary: "Full protocol and numeric table licensing require review; it cannot rate a general gym lift or another sport." },
  { id: "lesinski_2020_german_elite_youth", label: "German elite youth fitness reference", citationUrl: "https://pubmed.ncbi.nlm.nih.gov/32790710/", referencePopulation: "German elite sport-school athletes aged 8–18 years.", scope: "Named field tests matched by sex, age, maturation, and test version.", extraFields: ["bodyMassKgAtTest", "maturityStatus"], boundary: "It cannot become an adult, non-elite, sport-specific, or generic strength reference." },
  { id: "laurson_2017_nhanes_youth", label: "U.S. NHANES youth musculoskeletal reference", citationUrl: "https://pubmed.ncbi.nlm.nih.gov/27741055/", referencePopulation: "U.S. population youth aged 3–15 years.", scope: "Exact NNYFS handgrip, modified pull-up, or plank test variant.", extraFields: ["bodyMassKgAtTest", "heightCm"], boundary: "It cannot rate an adult, athlete-only cohort, ordinary pull-up, or unmatched handgrip protocol." },
  { id: "fitback_2023_european_youth", label: "FitBack European youth field-test reference", citationUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC9985767/", referencePopulation: "European children and adolescents aged 6–18 years.", scope: "ALPHA handgrip or standing-long-jump protocol only.", extraFields: ["laterality", "equipment"], boundary: "It cannot rate adult, athlete-specific, non-ALPHA, or body-size-transformed observations." },
  { id: "idefics_2014_european_children", label: "IDEFICS European child fitness reference", citationUrl: "https://pubmed.ncbi.nlm.nih.gov/25376221/", referencePopulation: "European children aged 6–10.9 years in the IDEFICS study.", scope: "Takei TKK 5101 handgrip or the stated standing-long-jump protocol.", extraFields: ["equipment"], boundary: "It cannot rate adolescents, athletes, another dynamometer, or another jump rule." },
  { id: "ma_2022_chinese_han_youth", label: "Chinese Han youth physical-fitness reference", citationUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC8762235/", referencePopulation: "Chinese Han schoolchildren aged 7–18 years.", scope: "Named national-survey test and normal-weight/total-population form.", extraFields: ["populationEthnicity", "bodyMassKgAtTest", "heightCm"], boundary: "It cannot rate a different ethnicity, country, test variant, athlete group, or inferred BMI category." },
  { id: "zhang_2021_chinese_youth", label: "Chinese youth physical-fitness reference", citationUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC7925655/", referencePopulation: "Chinese schoolchildren aged 7–18 years.", scope: "Exact grip, jump, or 30-second sit-up protocol.", extraFields: ["equipment"], boundary: "It cannot rate adult, athlete-specific, or differently timed/scored tests." },
  { id: "niessner_2020_momo", label: "MoMo German youth field-test reference", citationUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC7516256/", referencePopulation: "German representative youth aged 4–17 years.", scope: "MoMo 40-second push-up, 40-second sit-up, or standing-long-jump protocol.", extraFields: ["durationSeconds"], boundary: "It cannot rate older adults, athlete cohorts, or a conventional repetition test with another cadence or duration." },
  { id: "klein_2026_digimot", label: "DigiMot remote youth field-test reference", citationUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12913944/", referencePopulation: "German population youth aged 7–15 years in COMO-1.", scope: "Remote, one-trial, 40-second DigiMot push-up or sit-up protocol.", extraFields: ["durationSeconds", "administrationMode"], boundary: "It cannot rate in-person, multi-trial, adult, sport-specific, or unmatched-duration observations." },
  { id: "lee_2017_korean_adolescents", label: "Korean adolescent fitness reference", citationUrl: "https://pubmed.ncbi.nlm.nih.gov/31089495/", referencePopulation: "Korean adolescents aged 13–18 years.", scope: "Highest-of-trials handgrip or beep-paced partial curl-up protocol.", extraFields: ["equipment", "laterality"], boundary: "It cannot rate an athlete cohort, another country, a normal sit-up, or unverified scoring rules." },
  { id: "ramirez_velez_2017_fuprecol", label: "FUPRECOL Colombian schoolchild handgrip reference", citationUrl: "https://pubmed.ncbi.nlm.nih.gov/27135472/", referencePopulation: "Colombian schoolchildren aged 9–17.9 years.", scope: "Adjustable-grip hand dynamometry only.", extraFields: ["equipment", "laterality"], boundary: "Protocol details and numeric table rights require review; it cannot rate other grip methods or athlete populations." },
  { id: "martinez_torres_2022_colombian_handgrip", label: "Colombian youth handgrip reference", citationUrl: "https://pubmed.ncbi.nlm.nih.gov/35487284/", referencePopulation: "Colombian civilian youth aged 6–17.9 years.", scope: "Takei TKK 5101 handgrip, stated posture, scoring rule, and optional relative measure.", extraFields: ["bodyMassKgAtTest", "equipment", "laterality"], boundary: "It cannot rate adult, athlete-specific, different-dynamometer, or mixed scoring observations." },
  { id: "nevill_2025_nhanes_allometric_handgrip", label: "NHANES youth allometric handgrip reference", citationUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12476433/", referencePopulation: "U.S. civilian youth aged 6–19 years in NHANES.", scope: "Takei T.K.K.5401 maximum handgrip with source allometric normalization.", extraFields: ["bodyMassKgAtTest", "heightCm", "equipment", "laterality"], boundary: "It cannot substitute body-mass-only normalization or another dynamometer/score rule." },
  { id: "tunisian_adolescent_handgrip_2025", label: "Tunisian adolescent handgrip reference", citationUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12388144/", referencePopulation: "Healthy Tunisian adolescents aged 13–19 years.", scope: "Dominant-hand dynamometry on the fully verified study protocol.", extraFields: ["bodyMassKgAtTest", "heightCm", "laterality", "equipment"], boundary: "It cannot rate another population, nondominant hand, or a protocol not fully verified from the article." },
  { id: "bohannon_2017_youth_handgrip", label: "U.S. youth handgrip age-trajectory reference", citationUrl: "https://pubmed.ncbi.nlm.nih.gov/28350764/", referencePopulation: "Population-based youth aged 3–17 years.", scope: "One-hand-at-a-time handgrip protocol only.", extraFields: ["laterality", "equipment"], sourceAccess: "license_review_required", boundary: "It cannot rate adult, athlete, bilateral, or unmatched dynamometry observations." },
  { id: "pure_2015_adult_handgrip", label: "PURE adult international handgrip reference", citationUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC4833755/", referencePopulation: "Adults in 21-country PURE cohorts.", scope: "Jamar handgrip dynamometry only.", extraFields: ["equipment", "laterality"], sourceAccess: "context_only", boundary: "It cannot rate another dynamometer, youth, sport-specific cohort, or derived gym-grip score." },
  { id: "european_handgrip_reference_2025", label: "European adult dominant-hand handgrip reference", citationUrl: "https://pubmed.ncbi.nlm.nih.gov/41034601/", referencePopulation: "The study’s defined European adult sample.", scope: "Dominant-arm mechanical Smedley dynamometry only.", extraFields: ["equipment", "laterality"], boundary: "It cannot rate a different hand, device, protocol, or unverified population definition." },
  { id: "young_tennis_handgrip_2026", label: "Young tennis-player handgrip reference", citationUrl: "https://pubmed.ncbi.nlm.nih.gov/41765013/", referencePopulation: "The study’s young tennis-player cohort.", scope: "Dominant or nondominant handgrip as individually matched to the source protocol.", extraFields: ["sport", "laterality", "equipment"], sourceAccess: "license_review_required", expectedSport: "tennis", boundary: "Full methods and numeric use require review; it cannot represent general youth or non-tennis athletes." },
  { id: "senior_athlete_handgrip_2020", label: "Senior-athlete handgrip reference", citationUrl: "https://pubmed.ncbi.nlm.nih.gov/33354385/", referencePopulation: "The study’s senior athlete cohort.", scope: "Right/left and dominant/nondominant maximal handgrip outcomes only.", extraFields: ["sport", "laterality", "equipment"], sourceAccess: "license_review_required", boundary: "It cannot represent younger, non-athlete, or unmatched laterality/grip protocols." },
  { id: "young_athlete_nordbord_2023", label: "Young-athlete NordBord eccentric hamstring reference", citationUrl: "https://pubmed.ncbi.nlm.nih.gov/37867754/", referencePopulation: "The source’s young-athlete cohort.", scope: "NordBord Nordic hamstring eccentric knee-flexor strength normalized to body mass.", extraFields: ["bodyMassKgAtTest", "equipment", "laterality"], boundary: "It cannot rate a conventional hamstring curl, non-NordBord measure, or unnormalized force." },
  { id: "collegiate_football_nordbord_2026", label: "Collegiate American-football NordBord reference", citationUrl: "https://pubmed.ncbi.nlm.nih.gov/42506958/", referencePopulation: "The study’s collegiate American-football cohort.", scope: "NordBord eccentric hamstring strength by the source position and protocol fields.", extraFields: ["sport", "position", "equipment", "bodyMassKgAtTest", "laterality"], sourceAccess: "license_review_required", expectedSport: "football", boundary: "Full source access is required; it cannot rate another sport, device, position, or test variant." },
  { id: "soccer_hip_strength_2009", label: "Adult male association-football hip-strength reference", citationUrl: "https://pubmed.ncbi.nlm.nih.gov/19574097/", referencePopulation: "Adult male association-football players.", scope: "Handheld-dynamometer hip flexion/adduction at the stated hip angles.", extraFields: ["sport", "laterality", "equipment", "jointAngle"], sourceAccess: "license_review_required", expectedSport: "soccer", boundary: "It cannot rate general hip exercise, female athletes, another angle, or another dynamometer method." },
  { id: "male_soccer_hip_stiffness_2021", label: "Male soccer hip strength/flexibility/stiffness reference", citationUrl: "https://pubmed.ncbi.nlm.nih.gov/33197873/", referencePopulation: "The study’s male soccer-athlete cohort.", scope: "Source-specific isometric hip and flexibility/stiffness test measures.", extraFields: ["sport", "laterality", "equipment"], sourceAccess: "license_review_required", expectedSport: "soccer", boundary: "It cannot create a universal hip-strength percentile or a force estimate." },
  { id: "pro_hockey_hip_strength_2020", label: "Professional male ice-hockey hip reference", citationUrl: "https://pubmed.ncbi.nlm.nih.gov/32222647/", referencePopulation: "Professional male ice-hockey players.", scope: "Field hip adductor/abductor dynamometry and source ratio protocol.", extraFields: ["sport", "laterality", "equipment"], sourceAccess: "license_review_required", expectedSport: "hockey", boundary: "It cannot rate non-hockey, nonprofessional, injured-status, or unmatched hip tests." },
  { id: "navy_cadet_performance_2018", label: "Healthy Navy-cadet performance reference", citationUrl: "https://pubmed.ncbi.nlm.nih.gov/29351158/", referencePopulation: "Healthy Navy cadets.", scope: "Exact hip-strength, hop, plank, or flexibility test protocol.", extraFields: ["servicePopulation", "laterality", "equipment"], boundary: "It cannot rate general athletes or use one test as a global trunk/hip strength score." },
  { id: "collegiate_isometric_shoulder_2013", label: "Physically active collegiate isometric shoulder reference", citationUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC3548662/", referencePopulation: "Physically active collegiate males and females.", scope: "Named bilateral shoulder isometric positions only.", extraFields: ["laterality", "equipment", "jointAngle"], boundary: "It cannot rate dynamic pressing, another shoulder position, or a regional shoulder force value." },
  { id: "healthy_adult_isometric_shoulder_2023", label: "Healthy-adult isometric shoulder reference", citationUrl: "https://pubmed.ncbi.nlm.nih.gov/37547848/", referencePopulation: "The study’s healthy adult sample.", scope: "One of the seven named isometric shoulder positions.", extraFields: ["laterality", "equipment", "jointAngle"], boundary: "It cannot rate a different shoulder task, active athlete cohort, or combined shoulder score." },
  { id: "division_one_upper_extremity_2020", label: "Division I upper-extremity reference", citationUrl: "https://pubmed.ncbi.nlm.nih.gov/32330847/", referencePopulation: "Division I collegiate athletes.", scope: "Named shoulder isometric measure or CKCUEST touches protocol.", extraFields: ["sport", "laterality", "equipment"], boundary: "It cannot rate non-collegiate athletes, an unrelated upper-body lift, or modified CKCUEST." },
  { id: "overhead_athlete_upper_extremity_2018", label: "Overhead-athlete upper-extremity reference", citationUrl: "https://pubmed.ncbi.nlm.nih.gov/29564843/", referencePopulation: "The study’s overhead-athlete cohort.", scope: "YBT-UQ, CKCUEST, or seated medicine-ball throw only.", extraFields: ["sport", "laterality", "equipment"], sourceAccess: "license_review_required", boundary: "Full methods and numeric rights require review; no generic upper-body rating is permitted." },
  { id: "upper_limb_functional_testing_2025", label: "Upper-limb functional-test reference", citationUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC11733552/", referencePopulation: "The study’s age-, sex-, and sport-stratified participants.", scope: "Exact M-AST, SAMBT, SSASPT, ULRT, UQYBT, MCKCUEST, or PSET protocol.", extraFields: ["sport", "laterality", "equipment"], boundary: "It cannot combine test results or extrapolate to a general strength or injury conclusion." },
  { id: "taylor_2014_college_athletes", label: "College-athlete upper-extremity performance reference", citationUrl: "https://pubmed.ncbi.nlm.nih.gov/25611827/", referencePopulation: "The study’s college-athlete cohort.", scope: "CKCUEST or UQYBT exact protocol.", extraFields: ["sport", "laterality", "equipment"], boundary: "It cannot rate non-athletes, another sport context, or a modified test." },
  { id: "roush_2015_collegiate_baseball_ckcuest", label: "Collegiate baseball CKCUEST reference", citationUrl: "https://pubmed.ncbi.nlm.nih.gov/21522211/", referencePopulation: "Collegiate baseball players.", scope: "15-second CKCUEST hand-touch count.", extraFields: ["sport", "durationSeconds"], boundary: "It cannot rate a 20-second, modified, nonsport, or non-baseball test." },
  { id: "assef_2025_ncaa_football_ckcuest", label: "NCAA American-football CKCUEST reference", citationUrl: "https://pubmed.ncbi.nlm.nih.gov/40904720/", referencePopulation: "NCAA American-football players.", scope: "Source-specific CKCUEST protocol.", extraFields: ["sport", "position", "equipment"], boundary: "It cannot represent other sports, levels, or CKCUEST variants." },
  { id: "athlete_trunk_isometric_2021", label: "Athlete isometric-trunk strength reference", citationUrl: "https://pubmed.ncbi.nlm.nih.gov/34552035/", referencePopulation: "Athletes stratified by sex and sport in the source study.", scope: "Isometric trunk flexor, extensor, or lateral-flexor test and source ratios.", extraFields: ["sport", "laterality", "equipment"], sourceAccess: "license_review_required", boundary: "It cannot create a generic core score or health/injury inference." },
  { id: "harbo_2012_isokinetic_isometric", label: "Major-muscle isokinetic/isometric reference", citationUrl: "https://pubmed.ncbi.nlm.nih.gov/21537927/", referencePopulation: "The study’s sex- and age-stratified healthy population.", scope: "One of the source’s joint-, contraction-, and velocity-specific dynamometry protocols.", extraFields: ["laterality", "equipment", "jointAngle", "contractionMode"], boundary: "It cannot rate free-weight or gym exercise observations or merge different joint measures." },
  { id: "isokinetic_strength_review_2022", label: "Healthy-population isokinetic review", citationUrl: "https://pubmed.ncbi.nlm.nih.gov/36645122/", referencePopulation: "Heterogeneous healthy-population studies in a systematic review.", scope: "Context only until a specific underlying study and protocol are selected.", extraFields: ["laterality", "equipment", "jointAngle", "contractionMode"], sourceAccess: "context_only", boundary: "A heterogeneous review cannot supply a single percentile, tier, or generic reference table." },
  { id: "crossfit_imtp_cmj_2026", label: "CrossFit IMTP and CMJ profile", citationUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC13028203/", referencePopulation: "The study’s CrossFit-athlete cohort.", scope: "Two-trial IMTP or three-trial CMJ source protocol and force-time outcome.", extraFields: ["sport", "equipment", "bodyMassKgAtTest"], boundary: "It cannot rate a barbell lift, a generic jump, or infer sport performance beyond the source task." },
  { id: "calf_raise_application_2025", label: "Calf Raise Application heel-rise reference", citationUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC11923623/", referencePopulation: "The study’s general-population sample.", scope: "Dominant or nondominant single-leg heel-rise endurance via the validated Calf Raise Application.", extraFields: ["laterality", "administrationMode"], boundary: "It cannot rate weighted calf raises, bilateral raises, another app, or a generic calf strength value." },
] satisfies readonly AuditGateSpec[]).map((spec, index) => ({
  ...sourceSpecificGate(spec),
  auditRecordNumber: index < 15 ? index + 2 : index + 3,
}));
