/** Modern Kinetic Field Manual: compact per-exercise controls for a coach-editable training prescription. */
import { Check, ChevronDown, X } from "lucide-react";
import type { Exercise } from "@/lib/exerciseCatalog";
import { muscleLabels } from "@/components/AnatomyMap";
import type { ExerciseSettings } from "@/lib/workoutPlanner";
import "../mobile-training-card.css";

export function ExercisePrescriptionRow({ exercise, index, prescription, settings, onPrescription, onSettings, onInspect, onRemove }: { exercise: Exercise; index: number; prescription: string; settings: ExerciseSettings; onPrescription: (value: string) => void; onSettings: (patch: Partial<ExerciseSettings>) => void; onInspect: () => void; onRemove: () => void }) {
  const prescriptions = Array.from(new Set([prescription, "4 × 3–5", "3 × 6–10", "3 × 8–12", "3 × 12–15", "4 × 30 sec"]));
  const rpes = Array.from(new Set([settings.rpe, "RPE 6", "RPE 7", "RPE 8", "RPE 9"]));
  const rests = Array.from(new Set([settings.rest, "60 sec", "90 sec", "120 sec", "180 sec"]));
  return <div className={`custom-prescription ${settings.completed ? "custom-prescription-complete" : ""}`}><div className="custom-row"><span className="font-display text-2xl font-bold text-[#9cc4ea]">{String(index + 1).padStart(2, "0")}</span><button onClick={onInspect} className="min-w-0 flex-1 text-left"><p className="truncate text-sm font-bold text-white">{exercise.name}</p><p className="mt-1 text-[10px] text-[#c3d7ea]">{exercise.movement} · {exercise.primaryMuscles.map((muscle) => muscleLabels[muscle] || muscle).join(", ")}</p></button><div className="custom-row-actions"><select value={prescription} onChange={(event) => onPrescription(event.target.value)} className="h-9 min-w-0 flex-1 border border-[#7eabd2]/40 bg-[#0b2240] px-2 text-xs font-bold text-white outline-none" aria-label={`${exercise.name} prescription`}>{prescriptions.map((value) => <option key={value}>{value}</option>)}</select><button onClick={onRemove} className="grid h-9 w-9 shrink-0 place-items-center border border-[#7eabd2]/30 text-[#b7d8f4] hover:border-[#e4512e] hover:text-[#e4512e]" aria-label={`Remove ${exercise.name}`}><X className="h-4 w-4" /></button></div></div><div className="custom-detail-row"><label>RPE<select value={settings.rpe} onChange={(event) => onSettings({ rpe: event.target.value })}>{rpes.map((value) => <option key={value}>{value}</option>)}</select></label><label>Rest<select value={settings.rest} onChange={(event) => onSettings({ rest: event.target.value })}>{rests.map((value) => <option key={value}>{value}</option>)}</select></label><button onClick={() => onSettings({ completed: !settings.completed })} aria-pressed={settings.completed} className={`completion-toggle ${settings.completed ? "completion-toggle-on" : ""}`}>{settings.completed ? <Check className="h-3.5 w-3.5" /> : <span />} {settings.completed ? "Completed" : "Mark complete"}</button><details><summary>Coach note <ChevronDown className="h-3.5 w-3.5" /></summary><textarea value={settings.notes} onChange={(event) => onSettings({ notes: event.target.value })} placeholder="Technique cue, load, or substitution reason" /></details></div></div>;
}
