/** Gym Optimizer Exercise Genome: progressive analysis with teachable muscle and mechanics terminology. */
import { useMemo, useState } from "react";
import { Activity, BrainCircuit, ChartNoAxesCombined, CircleGauge, Dna, Info, Scale, ShieldAlert, Sparkles } from "lucide-react";
import type { Exercise } from "@/lib/exerciseCatalog";
import { analyzeExerciseContext, getExerciseGenome, getWorkoutGenome, type GenomeContext, type GenomeDimension } from "@/lib/exerciseGenome";
import { GradeStamp } from "@/components/GradeStamp";
import { exerciseEvidenceCoverage } from "@/lib/evidenceCoverage";

type Tab = "fingerprint" | "muscles" | "mechanics" | "context";
type LearnKey = GenomeDimension | "contribution" | "mechanicalLoading" | "longLengthLoading" | "peakContraction" | "stabilizationDemand" | "movementPattern" | "jointAction" | "forceDirection" | "kineticChain" | "stance" | "resistanceCurve" | "resistanceBias" | "stickingRegion" | "localFatigue" | "systemicFatigue" | "axialFatigue" | "gripFatigue";

const tabs: { id: Tab; label: string; icon: typeof Dna }[] = [
  { id: "fingerprint", label: "Fingerprint", icon: Dna },
  { id: "muscles", label: "Muscle Genome", icon: Activity },
  { id: "mechanics", label: "Mechanics", icon: CircleGauge },
  { id: "context", label: "Context", icon: BrainCircuit },
];

const labels: Record<GenomeDimension, string> = { hypertrophy: "Hypertrophy potential", strength: "Strength expression", power: "Power expression", stability: "Stability demand", mobility: "Mobility demand", sfr: "Stimulus-to-fatigue ratio", skill: "Technical skill demand", practicality: "Practicality" };
const termInfo: Record<LearnKey, { label: string; meaning: string; inputs: string; read: string }> = {
  hypertrophy: { label: labels.hypertrophy, meaning: "How well an exercise can support muscular size work.", inputs: "Target-muscle loading potential, usable range of motion, controllable resistance, and the ability to accumulate productive sets.", read: "Higher values usually indicate a more practical tool for local muscular work; they do not predict individual growth." },
  strength: { label: labels.strength, meaning: "How suitable an exercise is for developing high force.", inputs: "External load potential, compound force expression, bracing demands, and progression potential.", read: "Higher values indicate force-development potential within this model, not a one-repetition-maximum guarantee." },
  power: { label: labels.power, meaning: "How suitable an exercise is for fast force expression.", inputs: "Intent to move quickly, explosive coordination, and freedom to accelerate through the action.", read: "Higher values favor rapid force expression; actual power depends on load, intent, and execution." },
  stability: { label: labels.stability, meaning: "How much the exercise challenges positional control.", inputs: "Balance, unilateral control, bracing, external instability, and joint-position demands.", read: "Higher values mean more control demand, not automatically more benefit in every phase." },
  mobility: { label: labels.mobility, meaning: "How much usable movement range the exercise asks for.", inputs: "Joint excursion, end-range tolerance, and the positions required to perform the movement well.", read: "Higher values indicate greater positional demand; they are not a flexibility test." },
  sfr: { label: labels.sfr, meaning: "How much useful training stimulus the exercise can deliver relative to expected fatigue cost.", inputs: "Local loading, systemic and axial fatigue, technical complexity, setup demands, and repeatability.", read: "Higher values suggest a more repeatable stimulus-to-cost trade-off in this standardized comparison model." },
  skill: { label: labels.skill, meaning: "How much practice and coordination the movement normally requires.", inputs: "Timing, sequencing, technical constraints, and sensitivity to execution errors.", read: "Higher values mean more practice demand; this can be useful or inefficient depending on the goal." },
  practicality: { label: labels.practicality, meaning: "How straightforward the exercise is to use in a real program.", inputs: "Equipment access, setup time, available space, load changes, and predictable progression.", read: "Higher values reflect easier implementation, not superior physiology." },
  contribution: { label: "Muscle contribution", meaning: "The model's estimate of how directly a listed muscle contributes to the exercise.", inputs: "The muscle's role in the named joint actions, its line of pull, the exercise pattern, and whether it is a primary mover, helper, or stabilizer.", read: "A higher value means the muscle is more central to the task. It is an anatomical planning estimate, not an electromyography reading." },
  mechanicalLoading: { label: "Mechanical loading", meaning: "The estimated opportunity for a muscle to experience meaningful tension through the exercise.", inputs: "External resistance, leverage, range of motion, joint position, and whether the muscle can be progressively loaded.", read: "Higher values describe stronger tension potential for that muscle, not a direct measure of force in an individual repetition." },
  longLengthLoading: { label: "Long-length challenge", meaning: "How much the muscle may be loaded while relatively lengthened.", inputs: "Joint position at the deeper range, resistance curve, and whether resistance remains meaningful near the stretched position.", read: "Higher values mean the exercise more often challenges that muscle at longer lengths; it does not imply a mandatory training prescription." },
  peakContraction: { label: "Peak contraction", meaning: "How strongly the exercise can challenge the muscle near its shortened position.", inputs: "Resistance direction, leverage near end range, and whether tension remains high as the joint action finishes.", read: "Higher values indicate more shortened-range tension potential, not a universal measure of exercise quality." },
  stabilizationDemand: { label: "Stabilization demand", meaning: "How much positional control the muscle contributes while other joints produce the visible movement.", inputs: "Joint alignment, bracing, balance, unilateral demands, and resistance that could disturb position.", read: "Higher values mean the muscle has more control responsibility. This is different from being a prime mover." },
  movementPattern: { label: "Movement pattern", meaning: "The broad task family used to classify how the body moves.", inputs: "Primary displacement, force direction, joint sequencing, and whether the pattern is a squat, hinge, push, pull, carry, rotation, or locomotor task.", read: "Patterns help compare exercises and build balanced sessions; they do not replace individual technique analysis." },
  jointAction: { label: "Joint action", meaning: "The named motion occurring at a joint during the exercise.", inputs: "Observable motion such as flexion, extension, abduction, adduction, rotation, or scapular movement.", read: "A listed action describes the task mechanics; contribution from individual muscles can vary with setup and technique." },
  forceDirection: { label: "Force direction", meaning: "The dominant direction the athlete resists or applies force against the load.", inputs: "Load placement, gravity, cable or band line of pull, ground reaction force, and the intended movement path.", read: "It helps explain transfer and resistance behavior, but is a simplified descriptor of a three-dimensional task." },
  kineticChain: { label: "Kinetic chain", meaning: "Whether the moving limb is relatively free or fixed against an external surface.", inputs: "Contact with the floor, bench, bar, handles, or other stable surfaces during the exercise.", read: "Closed-chain tasks often coordinate multiple joints against a fixed contact; open-chain tasks usually allow a limb segment to move more freely." },
  stance: { label: "Stance", meaning: "The base-of-support configuration used during the exercise.", inputs: "Foot or hand contact pattern, unilateral versus bilateral setup, and whether the body is supported or free-standing.", read: "Stance influences balance, load sharing, and exercise constraints; it is not a score of athletic difficulty." },
  resistanceCurve: { label: "Resistance curve", meaning: "How the task's challenge changes from the start to the end of a repetition.", inputs: "Joint leverage, gravity or cable angle, external resistance, and equipment mechanics.", read: "The bars describe relative challenge across the modeled range, not a direct force trace for every machine or setup." },
  resistanceBias: { label: "Resistance bias", meaning: "The part of the range where the exercise tends to feel most mechanically demanding.", inputs: "The estimated resistance curve and the joint positions where leverage is least favorable.", read: "A bias label is a practical comparison cue; exercise setup can move the challenge within the range." },
  stickingRegion: { label: "Likely sticking region", meaning: "The range where a lifter may have the least mechanical advantage or greatest coordination challenge.", inputs: "Leverage, resistance direction, range of motion, and typical task constraints.", read: "It is a likely bottleneck, not a prediction that every athlete will fail at that exact point." },
  localFatigue: { label: "Local fatigue", meaning: "The expected fatigue concentrated in the muscles doing the work.", inputs: "Target-muscle loading, range of motion, contraction duration, and the amount of repeated local work.", read: "Higher values mean more localized fatigue cost in this comparison model." },
  systemicFatigue: { label: "Systemic fatigue", meaning: "The broader whole-body recovery cost the exercise can create.", inputs: "Total muscle mass involved, load, work duration, conditioning demand, and complexity.", read: "Higher values suggest the exercise may be more globally fatiguing; recovery differs by athlete and dosage." },
  axialFatigue: { label: "Axial fatigue", meaning: "The estimated loading and bracing cost through the trunk and spine.", inputs: "Spinal compression or shear exposure, torso angle, external load placement, and bracing demand.", read: "Higher values call for more attention to recovery and technique; they do not diagnose injury risk." },
  gripFatigue: { label: "Grip fatigue", meaning: "The expected fatigue cost to the hand and forearm gripping system.", inputs: "Handle demand, load, duration, forearm position, and whether the task limits work through grip.", read: "Higher values mean grip may become a limiting factor before the target muscles are fully challenged." },
};

function LearnButton({ label, onClick, className = "" }: { label: string; onClick: () => void; className?: string }) { return <button onClick={onClick} className={`genome-term-button ${className}`}>{label}<Info className="h-3 w-3" /></button>; }
function Meter({ label, value, tone = "blue", onLearn }: { label: string; value: number; tone?: "blue" | "ink" | "warm"; onLearn?: () => void }) { return <div className="genome-meter"><div className="flex items-center justify-between gap-2">{onLearn ? <LearnButton label={label} onClick={onLearn} /> : <span>{label}</span>}<strong>{value}</strong></div><span className={`genome-meter-track genome-meter-${tone}`}><i style={{ width: `${value}%` }} /></span></div>; }

export function ExerciseGenomePanel({ exercise, context }: { exercise: Exercise; context: GenomeContext }) {
  const [tab, setTab] = useState<Tab>("fingerprint");
  const [learnedTerm, setLearnedTerm] = useState<LearnKey | null>(null);
  const genome = useMemo(() => getExerciseGenome(exercise), [exercise]);
  const evidenceCoverage = useMemo(() => exerciseEvidenceCoverage(exercise), [exercise]);
  const analysis = useMemo(() => analyzeExerciseContext(exercise, context), [exercise, context]);
  const workoutGenome = useMemo(() => getWorkoutGenome(context.currentWorkout), [context.currentWorkout]);
  const radarPoints = useMemo(() => Object.entries(genome.fingerprint).map(([key, value], index, all) => { const angle = (Math.PI * 2 * index) / all.length - Math.PI / 2; const radius = 46 * (value / 100); return `${60 + Math.cos(angle) * radius},${60 + Math.sin(angle) * radius}`; }).join(" "), [genome.fingerprint]);
  const outerPoints = useMemo(() => Array.from({ length: 8 }, (_, index) => { const angle = (Math.PI * 2 * index) / 8 - Math.PI / 2; return `${60 + Math.cos(angle) * 46},${60 + Math.sin(angle) * 46}`; }).join(" "), []);
  const learn = (key: LearnKey) => () => setLearnedTerm(key);
  const fatigueTerms: Record<string, LearnKey> = { local: "localFatigue", systemic: "systemicFatigue", axial: "axialFatigue", grip: "gripFatigue" };

  return <section className="genome-panel"><div className="genome-panel-head"><div><p className="metric-label">Exercise Genome / decision-support model</p><h3 className="mt-1 font-display text-3xl font-bold uppercase leading-none text-[#0b2240]">What this tool adds</h3></div><div className="flex items-center gap-2"><span className="text-[10px] font-bold uppercase tracking-[.12em] text-[#547292]">Contextual fit</span><GradeStamp grade={analysis.grade} compact /></div></div><p className="mt-3 text-[10px] leading-4 text-[#657b92]">All 0–100 values below are standardized comparison indices generated from catalog mechanics and programming logic—not direct force, activation, fatigue, or laboratory measurements.</p><p className="mt-2 text-[10px] leading-4 text-[#657b92]"><strong>{evidenceCoverage.confidence} evidence coverage.</strong> {evidenceCoverage.sourceRange}. {evidenceCoverage.directScope} {evidenceCoverage.planningBoundary}</p><div className="genome-tabbar">{tabs.map((item) => { const Icon = item.icon; return <button key={item.id} onClick={() => setTab(item.id)} className={`genome-tab ${tab === item.id ? "genome-tab-active" : ""}`}><Icon className="h-3.5 w-3.5" />{item.label}</button>; })}</div>
    {tab === "fingerprint" && <div className="genome-grid"><div className="genome-fingerprint"><svg viewBox="0 0 120 120" aria-label="Exercise Genome fingerprint chart with eight labeled dimensions"><circle cx="60" cy="60" r="46" fill="none" stroke="#d2dfed" strokeWidth=".75" /><circle cx="60" cy="60" r="30" fill="none" stroke="#e2eaf4" strokeWidth=".75" /><polygon points={outerPoints} fill="none" stroke="#b9cce5" strokeWidth=".75" /><polygon points={radarPoints} fill="rgb(45 108 223 / .25)" stroke="#2d6cdf" strokeWidth="2" />{Object.keys(genome.fingerprint).map((key, index, all) => { const angle = (Math.PI * 2 * index) / all.length - Math.PI / 2; return <text key={key} x={60 + Math.cos(angle) * 55} y={61 + Math.sin(angle) * 55} textAnchor="middle" className="genome-radar-label">{labels[key as GenomeDimension].split(" ")[0]}</text>; })}</svg><p className="mt-1 text-center text-[10px] leading-4 text-[#657b92]">0 = little relative demand or opportunity. 100 = high relative demand or opportunity. Click a full label below to learn what influences it.</p></div><div className="genome-fingerprint-bars">{Object.entries(genome.fingerprint).map(([key, value]) => <Meter key={key} label={labels[key as GenomeDimension]} value={value} tone={key === "sfr" ? "warm" : "blue"} onLearn={learn(key as GenomeDimension)} />)}<div className="genome-fingerprint-legend">{Object.keys(genome.fingerprint).map((key) => <LearnButton key={key} label={labels[key as GenomeDimension]} onClick={learn(key as GenomeDimension)} />)}</div></div><div className="genome-quicknote"><Sparkles className="h-4 w-4 text-[#2d6cdf]" /><div><p className="metric-label">Fast read</p><p className="mt-1 text-xs leading-5 text-[#405b77]">{analysis.explanation}</p></div></div></div>}
    {tab === "muscles" && <div className="genome-muscle-stack"><div className="genome-section-intro"><p>Every term below is interactive. Use the information control to see what each comparative index means and what the model considers.</p></div>{genome.muscleProfile.map((entry) => <div className="genome-muscle-row" key={entry.muscle}><div className="flex min-w-0 items-start gap-3"><GradeStamp grade={entry.tier} compact /><div className="min-w-0"><p className="text-xs font-bold text-[#102b48]">{entry.anatomicalLabel}</p><LearnButton label={`${entry.role} · modelled ${entry.contribution}/100 involvement`} onClick={learn("contribution")} className="mt-0.5" /><p className="mt-2 text-[11px] leading-5 text-[#536b84]">{entry.why}</p></div></div><div className="grid min-w-[185px] grid-cols-2 gap-x-3 gap-y-2"><Meter label="Mechanical loading" value={entry.mechanicalLoading} onLearn={learn("mechanicalLoading")} /><Meter label="Long-length challenge" value={entry.longLengthLoading} tone="warm" onLearn={learn("longLengthLoading")} /><Meter label="Peak contraction" value={entry.peakContraction} onLearn={learn("peakContraction")} /><Meter label="Stabilization demand" value={entry.stabilizationDemand} tone="ink" onLearn={learn("stabilizationDemand")} /></div></div>)}</div>}
    {tab === "mechanics" && <div className="genome-mechanics"><div className="genome-mechanic-block"><LearnButton label="Movement pattern + joint action" onClick={learn("movementPattern")} className="metric-label" /><div className="mt-3 flex flex-wrap gap-2">{genome.movementPatterns.map((pattern) => <LearnButton key={pattern} label={pattern} onClick={learn("movementPattern")} className="genome-tag" />)}</div><div className="mt-4 flex flex-wrap gap-2">{genome.jointActions.map((action) => <LearnButton key={action} label={action} onClick={learn("jointAction")} className="genome-tag genome-tag-soft" />)}</div><div className="mt-4 flex flex-wrap gap-2 text-[11px] text-[#526b83]"><LearnButton label={`Force direction: ${genome.forceDirection}`} onClick={learn("forceDirection")} /><LearnButton label={`${genome.chain} chain`} onClick={learn("kineticChain")} /><LearnButton label={`${genome.stance.toLowerCase()} stance`} onClick={learn("stance")} /></div></div><div className="genome-mechanic-block"><LearnButton label="Resistance + fatigue curve" onClick={learn("resistanceCurve")} className="metric-label" /><div className="mt-4 genome-curve">{genome.resistanceProfile.curve.map((value, index) => <span key={index} style={{ height: `${value}%` }} />)}</div><div className="mt-3 grid grid-cols-2 gap-3 text-[11px] text-[#49637d]"><LearnButton label={`${genome.resistanceProfile.bias}-biased challenge profile`} onClick={learn("resistanceBias")} /><LearnButton label={`${genome.resistanceProfile.stickingRegion} likely sticking region`} onClick={learn("stickingRegion")} /></div><div className="mt-5 grid grid-cols-2 gap-3">{Object.entries(genome.fatigue).map(([key, value]) => <Meter key={key} label={`${key[0].toUpperCase()}${key.slice(1)} fatigue`} value={value} tone={key === "systemic" || key === "axial" ? "warm" : "ink"} onLearn={learn(fatigueTerms[key] || "localFatigue")} />)}</div></div></div>}
    {tab === "context" && <div className="genome-context"><div className="grid gap-3 sm:grid-cols-4"><div className="genome-stat"><p className="metric-label">Contextual utility</p><p className="font-display text-5xl font-bold text-[#0b2240]">{analysis.contextualScore}</p><p>summary, not a standalone verdict</p></div><div className="genome-stat"><p className="metric-label">Goal alignment</p><p className="font-display text-5xl font-bold text-[#2d6cdf]">{analysis.signals.goalAlignment}</p><p>relative match for your stated goal</p></div><div className="genome-stat"><p className="metric-label">Stack distinctness</p><p className="font-display text-5xl font-bold text-[#2d6cdf]">{analysis.signals.stackDistinctness}</p><p>what it adds beyond current work</p></div><div className="genome-stat"><p className="metric-label">Recovery manageability</p><p className="font-display text-5xl font-bold text-[#d06a38]">{analysis.signals.recoveryManageability}</p><p>relative cost from task fatigue signals</p></div></div><div className="genome-why"><Info className="h-4 w-4 text-[#2d6cdf]" /><div><p className="metric-label">Adaptation opportunity</p><p className="mt-1 text-xs leading-5 text-[#3e5873]">Primary: <strong>{genome.adaptation.primary.join(" · ")}</strong> · Secondary: <strong>{genome.adaptation.secondary.join(" · ")}</strong>. {genome.adaptation.rationale}</p></div></div><div className="genome-why"><Info className="h-4 w-4 text-[#2d6cdf]" /><div><p className="metric-label">Why this score changes</p><p className="mt-1 text-xs leading-5 text-[#3e5873]">{analysis.explanation} Sport-action match: {analysis.signals.sportActionMatch}/100.</p></div></div><div className="grid gap-3 md:grid-cols-2"><div className="genome-list"><p className="metric-label">What supports it</p>{analysis.strengths.map((item) => <p key={item}><ChartNoAxesCombined className="h-3.5 w-3.5" />{item}</p>)}</div><div className="genome-list genome-list-limits"><p className="metric-label">Trade-offs to consider</p>{analysis.limits.map((item) => <p key={item}><ShieldAlert className="h-3.5 w-3.5" />{item}</p>)}</div></div><div className="genome-stack-read"><div><p className="metric-label">Current Workout Genome</p><p className="mt-1 text-xs leading-5 text-[#45617c]">{workoutGenome.redundancy > 62 ? "The current stack repeats similar exposure. This exercise needs a specific role to earn its place." : "The stack has room for differentiated stimulus if this exercise fills a useful objective."}</p></div><div className="flex flex-wrap gap-1.5">{workoutGenome.gaps.slice(0, 3).map((gap) => <span key={gap} className="genome-tag genome-tag-soft">Missing {gap}</span>)}</div></div><p className="mt-4 text-[10px] leading-4 text-[#6a7e92]">Confidence: {genome.evidence.confidence} · {genome.evidence.quality}. {genome.evidence.note}</p></div>}
    {learnedTerm && <div className="genome-learn-overlay" role="dialog" aria-modal="true" aria-label={`${termInfo[learnedTerm].label} explained`}><div className="genome-learn-card"><button onClick={() => setLearnedTerm(null)} aria-label="Close term explanation" className="genome-learn-close">×</button><p className="metric-label">Genome term explained</p><h4>{termInfo[learnedTerm].label}</h4><p><strong>What it means.</strong> {termInfo[learnedTerm].meaning}</p><p><strong>What the model weighs.</strong> {termInfo[learnedTerm].inputs}</p><p><strong>How to read the number.</strong> {termInfo[learnedTerm].read}</p><div className="genome-learn-boundary">This is a standardized planning estimate for comparison—not a direct laboratory measurement, a medical assessment, or a universal recommendation.</div></div></div>}</section>;
}
