/** Gym Optimizer Exercise Genome: a progressive-disclosure analysis panel for exercise vectors and contextual utility. */
import { useMemo, useState } from "react";
import { Activity, BrainCircuit, ChartNoAxesCombined, CircleGauge, Dna, Info, Scale, ShieldAlert, Sparkles } from "lucide-react";
import type { Exercise } from "@/lib/exerciseCatalog";
import { analyzeExerciseContext, getExerciseGenome, getWorkoutGenome, type GenomeContext, type GenomeDimension } from "@/lib/exerciseGenome";
import { GradeStamp } from "@/components/GradeStamp";

type Tab = "fingerprint" | "muscles" | "mechanics" | "context";
const tabs: { id: Tab; label: string; icon: typeof Dna }[] = [
  { id: "fingerprint", label: "Fingerprint", icon: Dna },
  { id: "muscles", label: "Muscle Genome", icon: Activity },
  { id: "mechanics", label: "Mechanics", icon: CircleGauge },
  { id: "context", label: "Context", icon: BrainCircuit },
];
const labels: Record<GenomeDimension, string> = { hypertrophy: "Hypertrophy potential", strength: "Strength expression", power: "Power expression", stability: "Stability demand", mobility: "Mobility demand", sfr: "Stimulus-to-fatigue ratio", skill: "Technical skill demand", practicality: "Practicality" };

function Meter({ label, value, tone = "blue" }: { label: string; value: number; tone?: "blue" | "ink" | "warm" }) {
  return <div className="genome-meter"><div className="flex items-center justify-between gap-2"><span>{label}</span><strong>{value}</strong></div><span className={`genome-meter-track genome-meter-${tone}`}><i style={{ width: `${value}%` }} /></span></div>;
}

export function ExerciseGenomePanel({ exercise, context }: { exercise: Exercise; context: GenomeContext }) {
  const [tab, setTab] = useState<Tab>("fingerprint");
  const genome = useMemo(() => getExerciseGenome(exercise), [exercise]);
  const analysis = useMemo(() => analyzeExerciseContext(exercise, context), [exercise, context]);
  const workoutGenome = useMemo(() => getWorkoutGenome(context.currentWorkout), [context.currentWorkout]);
  const radarPoints = useMemo(() => Object.entries(genome.fingerprint).map(([key, value], index, all) => {
    const angle = (Math.PI * 2 * index) / all.length - Math.PI / 2;
    const radius = 46 * (value / 100);
    return `${60 + Math.cos(angle) * radius},${60 + Math.sin(angle) * radius}`;
  }).join(" "), [genome.fingerprint]);
  const outerPoints = useMemo(() => Array.from({ length: 8 }, (_, index) => {
    const angle = (Math.PI * 2 * index) / 8 - Math.PI / 2;
    return `${60 + Math.cos(angle) * 46},${60 + Math.sin(angle) * 46}`;
  }).join(" "), []);

  return <section className="genome-panel"><div className="genome-panel-head"><div><p className="metric-label">Exercise Genome / decision-support model</p><h3 className="mt-1 font-display text-3xl font-bold uppercase leading-none text-[#0b2240]">What this tool adds</h3></div><div className="flex items-center gap-2"><span className="text-[10px] font-bold uppercase tracking-[.12em] text-[#547292]">Contextual fit</span><GradeStamp grade={analysis.grade} compact /></div></div><div className="genome-tabbar">{tabs.map((item) => { const Icon = item.icon; return <button key={item.id} onClick={() => setTab(item.id)} className={`genome-tab ${tab === item.id ? "genome-tab-active" : ""}`}><Icon className="h-3.5 w-3.5" />{item.label}</button>; })}</div>
    {tab === "fingerprint" && <div className="genome-grid"><div className="genome-fingerprint"><svg viewBox="0 0 120 120" aria-label="Exercise Genome fingerprint chart"><circle cx="60" cy="60" r="46" fill="none" stroke="#d2dfed" strokeWidth=".75" /><circle cx="60" cy="60" r="30" fill="none" stroke="#e2eaf4" strokeWidth=".75" /><polygon points={outerPoints} fill="none" stroke="#b9cce5" strokeWidth=".75" /><polygon points={radarPoints} fill="rgb(45 108 223 / .25)" stroke="#2d6cdf" strokeWidth="2" /></svg><p className="mt-1 text-center text-[10px] leading-4 text-[#657b92]">Intrinsic fingerprint. Values summarize comparable exercise attributes rather than a universal verdict.</p></div><div className="genome-fingerprint-bars">{Object.entries(genome.fingerprint).map(([key, value]) => <Meter key={key} label={labels[key as GenomeDimension]} value={value} tone={key === "sfr" ? "warm" : "blue"} />)}</div><div className="genome-quicknote"><Sparkles className="h-4 w-4 text-[#2d6cdf]" /><div><p className="metric-label">Fast read</p><p className="mt-1 text-xs leading-5 text-[#405b77]">{analysis.explanation}</p></div></div></div>}
    {tab === "muscles" && <div className="genome-muscle-stack">{genome.muscleProfile.map((entry) => <div className="genome-muscle-row" key={entry.muscle}><div className="flex min-w-0 items-start gap-3"><GradeStamp grade={entry.tier} compact /><div className="min-w-0"><p className="text-xs font-bold text-[#102b48]">{entry.anatomicalLabel}</p><p className="mt-0.5 text-[10px] text-[#58708a]">{entry.role} · {entry.contribution}/100 involvement</p><p className="mt-2 text-[11px] leading-5 text-[#536b84]">{entry.why}</p></div></div><div className="grid min-w-[185px] grid-cols-2 gap-x-3 gap-y-2"><Meter label="LOAD" value={entry.mechanicalLoading} /><Meter label="LENGTH" value={entry.longLengthLoading} tone="warm" /><Meter label="PEAK" value={entry.peakContraction} /><Meter label="STAB" value={entry.stabilizationDemand} tone="ink" /></div></div>)}</div>}
    {tab === "mechanics" && <div className="genome-mechanics"><div className="genome-mechanic-block"><p className="metric-label">Movement + joint action</p><div className="mt-3 flex flex-wrap gap-2">{genome.movementPatterns.map((pattern) => <span key={pattern} className="genome-tag">{pattern}</span>)}</div><div className="mt-4 flex flex-wrap gap-2">{genome.jointActions.map((action) => <span key={action} className="genome-tag genome-tag-soft">{action}</span>)}</div><p className="mt-4 text-[11px] leading-5 text-[#526b83]">Force direction: <strong>{genome.forceDirection}</strong> · {genome.chain} chain · {genome.stance.toLowerCase()} stance</p></div><div className="genome-mechanic-block"><p className="metric-label">Resistance + fatigue curve</p><div className="mt-4 genome-curve">{genome.resistanceProfile.curve.map((value, index) => <span key={index} style={{ height: `${value}%` }} />)}</div><div className="mt-3 grid grid-cols-2 gap-3 text-[11px] text-[#49637d]"><p><strong className="block text-[#183452]">{genome.resistanceProfile.bias}-biased</strong> challenge profile</p><p><strong className="block text-[#183452]">{genome.resistanceProfile.stickingRegion}</strong> likely sticking region</p></div><div className="mt-5 grid grid-cols-2 gap-3">{Object.entries(genome.fatigue).map(([key, value]) => <Meter key={key} label={key.toUpperCase()} value={value} tone={key === "systemic" || key === "axial" ? "warm" : "ink"} />)}</div></div></div>}
    {tab === "context" && <div className="genome-context"><div className="grid gap-3 sm:grid-cols-3"><div className="genome-stat"><p className="metric-label">Contextual utility</p><p className="font-display text-5xl font-bold text-[#0b2240]">{analysis.contextualScore}</p><p>selected goal + sport action + stack</p></div><div className="genome-stat"><p className="metric-label">Marginal value</p><p className="font-display text-5xl font-bold text-[#2d6cdf]">{analysis.marginalValue}</p><p>what it adds beyond current work</p></div><div className="genome-stat"><p className="metric-label">Redundancy</p><p className="font-display text-5xl font-bold text-[#d06a38]">{analysis.redundancy}</p><p>overlap with current workout</p></div></div><div className="genome-why"><Info className="h-4 w-4 text-[#2d6cdf]" /><div><p className="metric-label">Why this score changes</p><p className="mt-1 text-xs leading-5 text-[#3e5873]">{analysis.explanation}</p></div></div><div className="grid gap-3 md:grid-cols-2"><div className="genome-list"><p className="metric-label">What supports it</p>{analysis.strengths.map((item) => <p key={item}><ChartNoAxesCombined className="h-3.5 w-3.5" />{item}</p>)}</div><div className="genome-list genome-list-limits"><p className="metric-label">Trade-offs to consider</p>{analysis.limits.map((item) => <p key={item}><ShieldAlert className="h-3.5 w-3.5" />{item}</p>)}</div></div><div className="genome-stack-read"><div><p className="metric-label">Current Workout Genome</p><p className="mt-1 text-xs leading-5 text-[#45617c]">{workoutGenome.redundancy > 62 ? "The current stack repeats similar exposure. This exercise needs a specific role to earn its place." : "The stack has room for differentiated stimulus if this exercise fills a useful objective."}</p></div><div className="flex flex-wrap gap-1.5">{workoutGenome.gaps.slice(0, 3).map((gap) => <span key={gap} className="genome-tag genome-tag-soft">Missing {gap}</span>)}</div></div><p className="mt-4 text-[10px] leading-4 text-[#6a7e92]">Confidence: {genome.evidence.confidence} · {genome.evidence.quality}. {genome.evidence.note}</p></div>}
  </section>;
}
