/** Gym Optimizer Exercise Genome: a progressive-disclosure analysis panel for exercise vectors and contextual utility. */
import { useMemo, useState } from "react";
import { Activity, BrainCircuit, ChartNoAxesCombined, CircleGauge, Dna, Info, Scale, ShieldAlert, Sparkles } from "lucide-react";
import type { Exercise } from "@/lib/exerciseCatalog";
import { analyzeExerciseContext, getExerciseGenome, getWorkoutGenome, type GenomeContext, type GenomeDimension } from "@/lib/exerciseGenome";
import { GradeStamp } from "@/components/GradeStamp";

type Tab = "fingerprint" | "muscles" | "mechanics" | "context";
const tabs: { id: Tab; label: string; icon: typeof Dna }[] = [
  { id: "fingerprint", label: "Fingerprint", icon: Dna },
  { id: "muscles", label: "Muscle Genome", icon: Activity },
  { id: "mechanics", label: "Mechanics", icon: CircleGauge },
  { id: "context", label: "Context", icon: BrainCircuit },
];
const labels: Record<GenomeDimension, string> = { hypertrophy: "Hypertrophy potential", strength: "Strength expression", power: "Power expression", stability: "Stability demand", mobility: "Mobility demand", sfr: "Stimulus-to-fatigue ratio", skill: "Technical skill demand", practicality: "Practicality" };
const termInfo: Record<GenomeDimension, { meaning: string; inputs: string; read: string }> = {
  hypertrophy: { meaning: "How well an exercise can support muscular size work.", inputs: "Target-muscle loading potential, usable range of motion, controllable resistance, and the ability to accumulate productive sets.", read: "Higher values usually indicate a more practical tool for accumulating local muscular work; they do not predict individual growth." },
  strength: { meaning: "How suitable an exercise is for developing high force.", inputs: "External load potential, compound force expression, bracing demands, and progression potential.", read: "Higher values indicate stronger force-development potential within this model, not a guarantee of a bigger one-repetition maximum." },
  power: { meaning: "How suitable an exercise is for fast force expression.", inputs: "Intent to move quickly, explosive coordination, and freedom to accelerate through the action.", read: "Higher values favor rapid force expression; actual power depends on load, intent, and execution." },
  stability: { meaning: "How much the exercise challenges positional control.", inputs: "Balance, unilateral control, bracing, external instability, and joint-position demands.", read: "Higher values mean more control demand, not automatically more benefit for every athlete or phase." },
  mobility: { meaning: "How much usable movement range the exercise asks for.", inputs: "Joint excursion, end-range tolerance, and the positions required to perform the movement well.", read: "Higher values indicate greater range and positional demand; they are not a flexibility test." },
  sfr: { meaning: "How much useful training stimulus the exercise can deliver relative to its expected fatigue cost.", inputs: "Local loading, systemic and axial fatigue, technical complexity, setup demands, and practical repeatability.", read: "Higher values suggest a more repeatable stimulus-to-cost trade-off in this standardized model." },
  skill: { meaning: "How much practice and coordination the movement usually requires.", inputs: "Timing, sequencing, technical constraints, and sensitivity to execution errors.", read: "Higher values mean more practice demand; that can be useful or inefficient depending on the goal." },
  practicality: { meaning: "How straightforward the exercise is to use in a real program.", inputs: "Equipment access, setup time, available space, load changes, and predictable progression.", read: "Higher values reflect easier implementation, not superior physiology." },
};

function Meter({ label, value, tone = "blue", onLearn }: { label: string; value: number; tone?: "blue" | "ink" | "warm"; onLearn?: () => void }) {
  return <div className="genome-meter"><div className="flex items-center justify-between gap-2">{onLearn ? <button onClick={onLearn} className="genome-term-button">{label}<Info className="h-3 w-3" /></button> : <span>{label}</span>}<strong>{value}</strong></div><span className={`genome-meter-track genome-meter-${tone}`}><i style={{ width: `${value}%` }} /></span></div>;
}

export function ExerciseGenomePanel({ exercise, context }: { exercise: Exercise; context: GenomeContext }) {
  const [tab, setTab] = useState<Tab>("fingerprint");
  const [learnedTerm, setLearnedTerm] = useState<GenomeDimension | null>(null);
  const genome = useMemo(() => getExerciseGenome(exercise), [exercise]);
  const analysis = useMemo(() => analyzeExerciseContext(exercise, context), [exercise, context]);
  const workoutGenome = useMemo(() => getWorkoutGenome(context.currentWorkout), [context.currentWorkout]);
  const radarPoints = useMemo(() => Object.entries(genome.fingerprint).map(([key, value], index, all) => {
    const angle = (Math.PI * 2 * index) / all.length - Math.PI / 2;
    const radius = 46 * (value / 100);
    return `${60 + Math.cos(angle) * radius},${60 + Math.sin(angle) * radius}`;
  }).join(" "), [genome.fingerprint]);
  const outerPoints = useMemo(() => Array.from({ length: 8 }, (_, index) => {
    const angle = (Math.PI * 2 * index) / 8 - Math.PI / 2;
    return `${60 + Math.cos(angle) * 46},${60 + Math.sin(angle) * 46}`;
  }).join(" "), []);

  return <section className="genome-panel"><div className="genome-panel-head"><div><p className="metric-label">Exercise Genome / decision-support model</p><h3 className="mt-1 font-display text-3xl font-bold uppercase leading-none text-[#0b2240]">What this tool adds</h3></div><div className="flex items-center gap-2"><span className="text-[10px] font-bold uppercase tracking-[.12em] text-[#547292]">Contextual fit</span><GradeStamp grade={analysis.grade} compact /></div></div><div className="genome-tabbar">{tabs.map((item) => { const Icon = item.icon; return <button key={item.id} onClick={() => setTab(item.id)} className={`genome-tab ${tab === item.id ? "genome-tab-active" : ""}`}><Icon className="h-3.5 w-3.5" />{item.label}</button>; })}</div>
    {tab === "fingerprint" && <div className="genome-grid"><div className="genome-fingerprint"><svg viewBox="0 0 120 120" aria-label="Exercise Genome fingerprint chart with eight labeled dimensions"><circle cx="60" cy="60" r="46" fill="none" stroke="#d2dfed" strokeWidth=".75" /><circle cx="60" cy="60" r="30" fill="none" stroke="#e2eaf4" strokeWidth=".75" /><polygon points={outerPoints} fill="none" stroke="#b9cce5" strokeWidth=".75" /><polygon points={radarPoints} fill="rgb(45 108 223 / .25)" stroke="#2d6cdf" strokeWidth="2" />{Object.keys(genome.fingerprint).map((key, index, all) => { const angle = (Math.PI * 2 * index) / all.length - Math.PI / 2; return <text key={key} x={60 + Math.cos(angle) * 55} y={61 + Math.sin(angle) * 55} textAnchor="middle" className="genome-radar-label">{labels[key as GenomeDimension].split(" ")[0]}</text>; })}</svg><p className="mt-1 text-center text-[10px] leading-4 text-[#657b92]">0 = little relative demand or opportunity. 100 = high relative demand or opportunity. Click a full label below to learn what influences it.</p></div><div className="genome-fingerprint-bars">{Object.entries(genome.fingerprint).map(([key, value]) => <Meter key={key} label={labels[key as GenomeDimension]} value={value} tone={key === "sfr" ? "warm" : "blue"} onLearn={() => setLearnedTerm(key as GenomeDimension)} />)}<div className="genome-fingerprint-legend">{Object.keys(genome.fingerprint).map((key) => <button key={key} onClick={() => setLearnedTerm(key as GenomeDimension)}>{labels[key as GenomeDimension]} <span>Learn</span></button>)}</div></div><div className="genome-quicknote"><Sparkles className="h-4 w-4 text-[#2d6cdf]" /><div><p className="metric-label">Fast read</p><p className="mt-1 text-xs leading-5 text-[#405b77]">{analysis.explanation}</p></div></div></div>}
    {tab === "muscles" && <div className="genome-muscle-stack">{genome.muscleProfile.map((entry) => <div className="genome-muscle-row" key={entry.muscle}><div className="flex min-w-0 items-start gap-3"><GradeStamp grade={entry.tier} compact /><div className="min-w-0"><p className="text-xs font-bold text-[#102b48]">{entry.anatomicalLabel}</p><p className="mt-0.5 text-[10px] text-[#58708a]">{entry.role} · {entry.contribution}/100 involvement</p><p className="mt-2 text-[11px] leading-5 text-[#536b84]">{entry.why}</p></div></div><div className="grid min-w-[185px] grid-cols-2 gap-x-3 gap-y-2"><Meter label="LOAD" value={entry.mechanicalLoading} /><Meter label="LENGTH" value={entry.longLengthLoading} tone="warm" /><Meter label="PEAK" value={entry.peakContraction} /><Meter label="STAB" value={entry.stabilizationDemand} tone="ink" /></div></div>)}</div>}
    {tab === "mechanics" && <div className="genome-mechanics"><div className="genome-mechanic-block"><p className="metric-label">Movement + joint action</p><div className="mt-3 flex flex-wrap gap-2">{genome.movementPatterns.map((pattern) => <span key={pattern} className="genome-tag">{pattern}</span>)}</div><div className="mt-4 flex flex-wrap gap-2">{genome.jointActions.map((action) => <span key={action} className="genome-tag genome-tag-soft">{action}</span>)}</div><p className="mt-4 text-[11px] leading-5 text-[#526b83]">Force direction: <strong>{genome.forceDirection}</strong> · {genome.chain} chain · {genome.stance.toLowerCase()} stance</p></div><div className="genome-mechanic-block"><p className="metric-label">Resistance + fatigue curve</p><div className="mt-4 genome-curve">{genome.resistanceProfile.curve.map((value, index) => <span key={index} style={{ height: `${value}%` }} />)}</div><div className="mt-3 grid grid-cols-2 gap-3 text-[11px] text-[#49637d]"><p><strong className="block text-[#183452]">{genome.resistanceProfile.bias}-biased</strong> challenge profile</p><p><strong className="block text-[#183452]">{genome.resistanceProfile.stickingRegion}</strong> likely sticking region</p></div><div className="mt-5 grid grid-cols-2 gap-3">{Object.entries(genome.fatigue).map(([key, value]) => <Meter key={key} label={key.toUpperCase()} value={value} tone={key === "systemic" || key === "axial" ? "warm" : "ink"} />)}</div></div></div>}
    {tab === "context" && <div className="genome-context"><div className="grid gap-3 sm:grid-cols-3"><div className="genome-stat"><p className="metric-label">Contextual utility</p><p className="font-display text-5xl font-bold text-[#0b2240]">{analysis.contextualScore}</p><p>selected goal + sport action + stack</p></div><div className="genome-stat"><p className="metric-label">Marginal value</p><p className="font-display text-5xl font-bold text-[#2d6cdf]">{analysis.marginalValue}</p><p>what it adds beyond current work</p></div><div className="genome-stat"><p className="metric-label">Redundancy</p><p className="font-display text-5xl font-bold text-[#d06a38]">{analysis.redundancy}</p><p>overlap with current workout</p></div></div><div className="genome-why"><Info className="h-4 w-4 text-[#2d6cdf]" /><div><p className="metric-label">Why this score changes</p><p className="mt-1 text-xs leading-5 text-[#3e5873]">{analysis.explanation}</p></div></div><div className="grid gap-3 md:grid-cols-2"><div className="genome-list"><p className="metric-label">What supports it</p>{analysis.strengths.map((item) => <p key={item}><ChartNoAxesCombined className="h-3.5 w-3.5" />{item}</p>)}</div><div className="genome-list genome-list-limits"><p className="metric-label">Trade-offs to consider</p>{analysis.limits.map((item) => <p key={item}><ShieldAlert className="h-3.5 w-3.5" />{item}</p>)}</div></div><div className="genome-stack-read"><div><p className="metric-label">Current Workout Genome</p><p className="mt-1 text-xs leading-5 text-[#45617c]">{workoutGenome.redundancy > 62 ? "The current stack repeats similar exposure. This exercise needs a specific role to earn its place." : "The stack has room for differentiated stimulus if this exercise fills a useful objective."}</p></div><div className="flex flex-wrap gap-1.5">{workoutGenome.gaps.slice(0, 3).map((gap) => <span key={gap} className="genome-tag genome-tag-soft">Missing {gap}</span>)}</div></div><p className="mt-4 text-[10px] leading-4 text-[#6a7e92]">Confidence: {genome.evidence.confidence} · {genome.evidence.quality}. {genome.evidence.note}</p></div>}
  {learnedTerm && <div className="genome-learn-overlay" role="dialog" aria-modal="true" aria-label={`${labels[learnedTerm]} explained`}><div className="genome-learn-card"><button onClick={() => setLearnedTerm(null)} aria-label="Close term explanation" className="genome-learn-close">×</button><p className="metric-label">Genome term explained</p><h4>{labels[learnedTerm]}</h4><p><strong>What it means.</strong> {termInfo[learnedTerm].meaning}</p><p><strong>What the model weighs.</strong> {termInfo[learnedTerm].inputs}</p><p><strong>How to read the number.</strong> {termInfo[learnedTerm].read}</p><div className="genome-learn-boundary">This is a standardized planning estimate for comparison—not a direct laboratory measurement or a universal recommendation.</div></div></div>}</section>;
}
