import { useState } from "react";
import { AlertTriangle, Check, ChevronDown, CircleDot, ExternalLink, Layers3, Plus, ShieldAlert } from "lucide-react";
import type { Exercise } from "@/lib/exerciseCatalog";
import type { EnrichedSportMovement } from "@/lib/enrichedSportMovementDatabase";
import { analyzeWorkoutForMovement, getMovementAssistance, type WorkoutMovementAnalysis } from "@/lib/movementProgramAnalysis";
import type { SportMovementProfile } from "@/lib/sportMovementDatabase";
import { getSprintPowerEvidenceContext } from "@/lib/sprintPowerEvidence";
import { SprintPowerEvidenceDisclosure } from "@/components/SprintPowerEvidenceDisclosure";

/** Modern Kinetic Field Manual: lead with coverage and assistance; expose full anatomy, overlap, and sources only when requested. */
function RoleList({ title, entries }: { title: string; entries: ReturnType<typeof analyzeWorkoutForMovement>["primeMovers"] }) {
  return <div className="movement-role-group"><p className="metric-label">{title}</p><div className="mt-2 space-y-1.5">{entries.map((entry) => <div key={`${title}-${entry.name}`} className={`movement-role-row ${entry.coveredBy.length ? "movement-role-covered" : ""}`}><span>{entry.coveredBy.length ? <Check className="h-3.5 w-3.5" /> : <CircleDot className="h-3.5 w-3.5" />}</span><div className="min-w-0 flex-1"><p>{entry.name}</p><small>{entry.coveredBy.length ? `Covered by ${entry.coveredBy.map((exercise) => exercise.name).join(" · ")}` : "Coverage opportunity in the current stack"}</small></div></div>)}</div></div>;
}

export function MovementIntelligencePanel({ movement, fallback, workout, onAdd, onInspect, compact = false }: { movement?: EnrichedSportMovement; fallback: SportMovementProfile; workout: Exercise[]; onAdd?: (exercise: Exercise) => void; onInspect?: (exercise: Exercise) => void; compact?: boolean }) {
  const [showAllAssistance, setShowAllAssistance] = useState(false);
  if (!movement) return <div className="light-panel p-5"><p className="metric-label">Research enrichment pending</p><p className="mt-2 text-sm text-[#607069]">This action remains available through the existing movement profile while its detailed research record is loaded.</p></div>;
  const analysis = analyzeWorkoutForMovement(movement, workout);
  const assistance = getMovementAssistance(movement, fallback, compact ? 4 : 6);
  const shownAssistance = showAllAssistance ? assistance : assistance.slice(0, 3);
  const sprintPowerEvidence = getSprintPowerEvidenceContext(movement);

  return <section className={`movement-intelligence-panel ${compact ? "movement-intelligence-compact" : ""}`}>
    <div className="movement-intelligence-head"><div><p className="metric-label">Movement intelligence</p><h3>{movement.label}</h3><p>{movement.commonForceOrSkillDemand}</p></div><span className={`confidence-badge confidence-${movement.evidenceConfidence}`}>{movement.evidenceConfidence} confidence</span></div>
    <div className="movement-summary-strip"><div><span>Primary demand</span><strong>{movement.bodyActions.slice(0, 2).join(" · ")}</strong></div><div><span>Best-supported qualities</span><strong>{analysis.coverage.strengths.length ? analysis.coverage.strengths.slice(0, 2).join(" · ") : "Build the first training signal"}</strong></div><div><span>First priority</span><strong>{analysis.coverage.priorities[0] || "Maintain current balance"}</strong></div></div>
    <p className="movement-specificity-note"><strong>Specificity boundary:</strong> Sport practice remains the highest-specificity stimulus. These gym options support the movement demands; they do not replace the sporting action.</p>
    {sprintPowerEvidence && <SprintPowerEvidenceDisclosure evidence={sprintPowerEvidence} compact={compact} />}
    <section className="movement-coverage-conclusion"><div><p className="metric-label">Training coverage</p><strong>{analysis.coverage.percent}%</strong><span>{analysis.coverage.percent >= 75 ? "Well supported for this action" : analysis.coverage.percent >= 45 ? "Base is in place; targeted support can help" : "Several movement demands still need direct work"}</span></div><div><p>Strong coverage</p>{analysis.coverage.strengths.length ? analysis.coverage.strengths.map((item) => <span key={item}>✓ {item}</span>) : <span>Start by adding a primary movement match.</span>}</div><div><p>Needs more work</p>{analysis.coverage.priorities.length ? analysis.coverage.priorities.map((item) => <span key={item}>→ {item}</span>) : <span>Current stack covers the mapped requirements.</span>}</div></section>

    <div className="movement-section-heading"><Layers3 className="h-4 w-4" /><span>Gym support for this action</span></div>
    <div className="movement-assistance-list">{shownAssistance.map((item, index) => <div key={item.exercise.id} className="movement-assistance-row"><span className="movement-assistance-index">{String(index + 1).padStart(2, "0")}</span><button onClick={() => onInspect?.(item.exercise)} className="movement-assistance-content"><strong>{item.exercise.name}</strong><small>{item.rationale}</small><em>{item.source === "Movement record" ? "Movement-transfer support" : "Strength-capacity support"} · {movement.evidenceConfidence} evidence context</em></button><span className="movement-assistance-source">{item.source}</span>{onAdd && <button onClick={() => onAdd(item.exercise)} className="movement-assistance-add" aria-label={`Add ${item.exercise.name}`}><Plus className="h-4 w-4" /></button>}</div>)}</div>
    {assistance.length > 3 && <button className="movement-show-more" onClick={() => setShowAllAssistance((value) => !value)}>{showAllAssistance ? "Show fewer support exercises" : `See ${assistance.length - 3} more support exercises`}<ChevronDown className={`h-4 w-4 ${showAllAssistance ? "rotate-180" : ""}`} /></button>}

    <details className="movement-disclosure"><summary>View all {analysis.coverage.total} requirements and mechanics <ChevronDown className="h-4 w-4" /></summary><div className="movement-joint-grid"><div><p className="metric-label">Body actions</p><p>{movement.bodyActions.join(" · ")}</p></div><div><p className="metric-label">Joint actions</p><p>{movement.jointActions.join(" · ")}</p></div><div><p className="metric-label">Contraction roles</p><p>{movement.contractionRoles.join(" · ")}</p></div></div><div className="movement-role-grid"><RoleList title="Prime movers" entries={analysis.primeMovers} /><RoleList title="Assisting muscles" entries={analysis.assistingMuscles} /><RoleList title="Stabilizers" entries={analysis.stabilizers} /></div></details>

    <details className="movement-disclosure"><summary>Review overlap and programming cautions <ChevronDown className="h-4 w-4" /></summary><div className="redundancy-panel"><div><p className="metric-label">Workout overlap review</p><p>{analysis.redundancyFlags.length ? `${analysis.redundancyFlags.length} pair${analysis.redundancyFlags.length === 1 ? "" : "s"} worth reviewing.` : "No close same-pattern overlaps detected in this stack."}</p></div>{analysis.redundancyFlags.length ? <div className="mt-3 space-y-2">{analysis.redundancyFlags.map((flag) => <div key={`${flag.left.id}-${flag.right.id}`} className="redundancy-row"><ShieldAlert className="h-4 w-4" /><div><strong>{flag.level}: {flag.left.name} + {flag.right.name}</strong><small>{flag.rationale}</small></div></div>)}</div> : <div className="redundancy-clear"><Check className="h-4 w-4" /> No alert does not mean the session is optimal; review volume, prescription, and recovery context.</div>}</div><div className="movement-caution"><AlertTriangle className="h-4 w-4" /><p>{movement.exerciseSelectionCautions}</p></div>{!compact && <div className="movement-sources"><span>Evidence sources</span>{movement.sources.slice(0, 3).map((source) => <a href={source} key={source} target="_blank" rel="noreferrer"><ExternalLink className="h-3 w-3" /> Source</a>)}</div>}</details>
  </section>;
}
