/** Modern Kinetic Field Manual: an explicit searchable movement-analysis route for the full sport-action database. */
import { ArrowUpRight, Search } from "lucide-react";
import type { SportMovementProfile, SportProfile } from "@/lib/sportMovementDatabase";

export function MovementAtlasPanel({ sportName, sportId, sports, movements, selectedMovement, query, family, onQuery, onFamily, onSport, onMovement, onOpenBody }: { sportName: string; sportId: string; sports: SportProfile[]; movements: SportMovementProfile[]; selectedMovement: SportMovementProfile; query: string; family: string; onQuery: (value: string) => void; onFamily: (value: string) => void; onSport: (sportId: string) => void; onMovement: (movement: SportMovementProfile) => void; onOpenBody: () => void }) {
  const families = Array.from(new Set(movements.map((movement) => movement.family))).sort();
  const normalized = query.trim().toLowerCase();
  const visible = movements.filter((movement) => (family === "All" || movement.family === family) && (!normalized || `${movement.label} ${movement.family} ${movement.bodyActions} ${movement.primaryMuscles}`.toLowerCase().includes(normalized)));
  return <section className="movement-atlas-improved"><header className="atlas-improved-head"><div><p className="metric-label">05 / movement atlas</p><h1>Every action.<br /><em>Easy to inspect.</em></h1><p>{sportName} has {movements.length} researched actions in the current lens. Filter by family or search a body action, muscle, or skill.</p></div><div className="atlas-inventory"><strong>{visible.length}</strong><span>matching actions<br />400 total records</span></div></header><div className="atlas-tool-row"><div className="atlas-sport-select"><span>Sport lens</span><select value={sportId} onChange={(event) => onSport(event.target.value)}>{sports.map((sport) => <option key={sport.id} value={sport.id}>{sport.label}</option>)}</select></div><label><Search className="h-4 w-4" /><input value={query} onChange={(event) => onQuery(event.target.value)} placeholder="Search actions, muscles, or body mechanics" /></label><div className="atlas-family-row"><button onClick={() => onFamily("All")} aria-pressed={family === "All"}>All</button>{families.map((item) => <button key={item} onClick={() => onFamily(item)} aria-pressed={family === item}>{item}</button>)}</div></div><div className="atlas-analysis-grid"><div className="atlas-action-list">{visible.length ? visible.map((movement, index) => <button key={movement.id} onClick={() => onMovement(movement)} aria-pressed={movement.id === selectedMovement.id} className="atlas-action-item"><span>{String(index + 1).padStart(2, "0")}</span><div><strong>{movement.label}</strong><small>{movement.family}</small></div><ArrowUpRight className="h-4 w-4" /></button>) : <div className="atlas-empty"><strong>No actions match this filter.</strong><p>Clear the family filter or search a broader body-action term.</p></div>}</div><article className="atlas-focus-card"><p className="metric-label">Selected action / field note</p><h2>{selectedMovement.label}</h2><p>{selectedMovement.bodyActions}</p><dl><div><dt>Prime movers</dt><dd>{selectedMovement.primaryMuscles}</dd></div><div><dt>Stabilizers</dt><dd>{selectedMovement.stabilizers}</dd></div><div><dt>Training transfer</dt><dd>{selectedMovement.gymTransferCue}</dd></div></dl><button onClick={onOpenBody}>Trace this action in Body Lab <ArrowUpRight className="h-4 w-4" /></button></article></div></section>;
}
