import { Activity, ArrowUpRight, CalendarDays, Dumbbell, Sparkles } from "lucide-react";
import { trpc } from "@/lib/trpc";

export function ProgressOverviewPanel({ onOpenStrength, onOpenTraining }: { onOpenStrength: () => void; onOpenTraining: () => void }) {
  const sessions = trpc.workoutLog.list.useQuery();
  const observations = trpc.strengthGenome.observations.useQuery();
  const completedSessions = sessions.data?.filter(session => session.status === "completed") || [];
  const latestSession = completedSessions[0];
  const latestObservation = observations.data?.[0];

  return <section className="space-y-5"><div className="view-header"><div><p className="metric-label">Your training record</p><h1 className="mt-2 font-display text-5xl font-bold uppercase leading-[.82] text-[#102947]">Progress from<br /><em className="text-[#2d6cdf]">real work.</em></h1><p className="mt-4 max-w-2xl text-sm leading-6 text-[#53718d]">Review completed sessions and performance observations. New comparisons appear only when there is enough saved information to make the view useful.</p></div><div className="view-header-note"><Activity className="h-5 w-5 text-[#2d6cdf]" /><p>Training history, strength observations, and planning context remain separate from health or athlete-readiness claims.</p></div></div>
    <div className="grid gap-4 md:grid-cols-2"><section className="dark-panel p-5"><div className="flex items-start justify-between gap-4"><div><p className="metric-label !text-[#a9bed4]">Completed training days</p><p className="mt-2 font-display text-6xl font-bold leading-none text-white">{completedSessions.length}</p><p className="mt-3 text-xs leading-5 text-[#c4d3e2]">{latestSession ? `Latest: ${latestSession.title}` : "Complete a planned training day to begin your session history."}</p></div><CalendarDays className="h-7 w-7 text-[#f2c14d]" /></div><button type="button" onClick={onOpenTraining} className="mt-5 inline-flex min-h-11 items-center gap-2 rounded-xl border border-white/20 px-3 text-[10px] font-bold uppercase tracking-[.12em] text-white hover:border-[#f2c14d] hover:text-[#f2c14d]">Review Training Days <ArrowUpRight className="h-4 w-4" /></button></section>
      <section className="light-panel p-5"><div className="flex items-start justify-between gap-4"><div><p className="metric-label">Strength observations</p><p className="mt-2 font-display text-6xl font-bold leading-none text-[#102947]">{observations.data?.length || 0}</p><p className="mt-3 text-xs leading-5 text-[#607b91]">{latestObservation ? `Latest: ${latestObservation.exerciseName}` : "Log a standardized lift or test to begin your private performance history."}</p></div><Dumbbell className="h-7 w-7 text-[#e4512e]" /></div><button type="button" onClick={onOpenStrength} className="mt-5 inline-flex min-h-11 items-center gap-2 rounded-xl bg-[#e4512e] px-3 text-[10px] font-bold uppercase tracking-[.12em] text-white hover:bg-[#c84323]">Open Strength Genome <Sparkles className="h-4 w-4" /></button></section></div>
    <section className="light-panel p-5"><p className="metric-label">Next best action</p><h2 className="mt-1 font-display text-3xl font-bold uppercase leading-none text-[#102947]">Keep the record useful.</h2>{!completedSessions.length && !observations.data?.length ? <p className="mt-3 max-w-2xl text-sm leading-6 text-[#5d788f]">Start with either a completed training day or a standardized performance observation. Sports Genome will not create a progress story from missing data.</p> : <p className="mt-3 max-w-2xl text-sm leading-6 text-[#5d788f]">Continue adding comparable training records. Personal trends become more useful as the same movement or test is repeated under documented conditions.</p>}</section>
  </section>;
}
