import { AlertTriangle, CheckCircle2, ChevronDown, Moon } from "lucide-react";
import type { TrainingGoal } from "@/lib/workoutPlanner";
import type { WeeklyPlan, WeeklyPrescriptionStore } from "@/lib/weeklyVolume";
import { getRecoverySpacingAlerts } from "@/lib/recoverySpacing";
import "../recovery-spacing.css";

export function RecoverySpacingPanel({ plan, prescriptions, goal }: { plan: WeeklyPlan; prescriptions: WeeklyPrescriptionStore; goal: TrainingGoal }) {
  const alerts = getRecoverySpacingAlerts(plan, prescriptions, goal);
  const savedDays = Object.values(plan).filter((workout) => workout.length).length;
  return <section className="recovery-spacing-panel" aria-label="Recovery spacing between saved training days"><div className="recovery-spacing-head"><div><p className="metric-label">Saved-week spacing</p><h3>Recovery spacing</h3><p>{savedDays < 2 ? "Save at least two training days to check how demanding muscle exposure is spaced." : alerts.length ? `${alerts.length} consecutive-day overlap${alerts.length === 1 ? " needs" : "s need"} review.` : "No high-exposure muscle overlap appears across consecutive saved days."}</p></div>{alerts.length ? <AlertTriangle className="h-5 w-5" /> : <CheckCircle2 className="h-5 w-5" />}</div>{alerts.length ? <div className="recovery-spacing-list">{alerts.map((alert) => <article key={`${alert.previousDay}-${alert.nextDay}`} className={`recovery-spacing-${alert.severity}`}><div><strong>{alert.previousDay} → {alert.nextDay}</strong><small>{alert.severity === "priority" ? "High repeated exposure" : "Repeated exposure to watch"}</small></div><p>{alert.sharedMuscles.slice(0, 3).map((muscle) => `${muscle.label} (${muscle.previousSets}/${muscle.nextSets} sets)`).join(" · ")}</p><em>{alert.severity === "priority" ? "Consider moving one focused muscle slot, lowering next-day direct sets, or inserting a lower-overlap day." : "Keep the second session’s effort and exercise selection intentional; adjust if performance or soreness lingers."}</em></article>)}</div> : <div className="recovery-spacing-clear"><Moon className="h-4 w-4" /><span>Spacing check clear for the saved plan. This does not replace individual readiness, sleep, sport-practice, or pain monitoring.</span></div>}<details className="recovery-spacing-details"><summary>How this spacing check works <ChevronDown className="h-4 w-4" /></summary><p>It compares adjacent saved days only. A muscle is surfaced when it has at least three estimated sets on both days; primary-muscle sets count fully and supporting-muscle exposure counts at half. The result is a planning prompt—not a recovery, injury, or medical assessment.</p></details></section>;
}
