import { ArrowLeft, ArrowLeftRight, ArrowRight, ChevronDown, X } from "lucide-react";
import type { SplitDay } from "@/lib/splitCycle";
import { loadoutTemplateRules, type TrainingLoadout } from "@/lib/loadoutTemplates";
import "./SplitDraftControls.css";

/** Modern Kinetic Field Manual: a compact planner panel that opens only on demand and never claims the active workspace. */
export type { SplitDay } from "@/lib/splitCycle";
export type LoadoutMode = TrainingLoadout;

export function SplitDraftControls({ days, activeDayIndex, activeLoadout, onDay, onCycle, onLoadout, onDraft, onClose, onMove }: { days: SplitDay[]; activeDayIndex: number; activeLoadout: LoadoutMode; onDay: (day: SplitDay, index: number) => void; onCycle: (direction: -1 | 1) => void; onLoadout: (loadout: LoadoutMode) => void; onDraft: () => void; onClose: () => void; onMove: () => void }) {
  const activeDay = days[activeDayIndex] || days[0];
  return <div className="split-draft-controls"><div className="planner-panel-head"><div><p className="metric-label">Session planner</p><p className="mt-1 text-sm font-bold text-white">Draft without leaving your work.</p></div><div className="flex items-center gap-1"><button onClick={onMove} className="planner-icon-button" title="Move planner to the other screen edge" aria-label="Move planner"><ArrowLeftRight className="h-4 w-4" /></button><button onClick={onClose} className="planner-icon-button" title="Close planner" aria-label="Close planner"><X className="h-4 w-4" /></button></div></div><div className="split-row"><div className="flex items-center justify-between gap-2"><p className="metric-label">Training day</p><div className="flex items-center gap-1"><button onClick={() => onCycle(-1)} className="planner-icon-button" title="Previous training day" aria-label="Previous training day"><ArrowLeft className="h-3.5 w-3.5" /></button><span className="split-cycle-label" aria-live="polite">Day {String(activeDayIndex + 1).padStart(2, "0")} · {activeDay}</span><button onClick={() => onCycle(1)} className="planner-icon-button" title="Next training day" aria-label="Next training day"><ArrowRight className="h-3.5 w-3.5" /></button></div></div><div className="split-chip-row">{days.map((day, index) => <button key={`${day}-${index}`} onClick={() => onDay(day, index)} className={`split-chip ${index === activeDayIndex ? "split-chip-active" : ""}`}><span>{String(index + 1).padStart(2, "0")}</span>{day}</button>)}</div><p className="split-helper">Suggested for {days.length} training day{days.length === 1 ? "" : "s"}; choose any chip to override the sequence.</p></div><div className="split-row split-row-loadout"><p className="metric-label">Loadout orientation</p><div className="split-chip-row">{(Object.keys(loadoutTemplateRules) as LoadoutMode[]).map((loadout) => <button key={loadout} onClick={() => onLoadout(loadout)} title={loadoutTemplateRules[loadout].description} className={`loadout-chip ${loadout === activeLoadout ? "loadout-chip-active" : ""}`}>{loadout}</button>)}</div><div className="mt-3 flex items-center justify-between gap-3"><p className="split-helper">{loadoutTemplateRules[activeLoadout].description}</p><button onClick={onDraft} className="split-draft-button">Draft this session</button></div></div><button onClick={onClose} className="planner-collapse-link">Collapse planner <ChevronDown className="h-3.5 w-3.5" /></button></div>;
}
