/** Kinetic Field Manual: week-level muscle exposure from saved day prescriptions, not a medical readiness metric. */
import { BarChart3, ChevronDown, Layers3 } from "lucide-react";
import type { TrainingGoal } from "@/lib/workoutPlanner";
import { getVolumeStatus, getWeeklyMuscleVolume, type WeeklyPlan, type WeeklyPrescriptionStore } from "@/lib/weeklyVolume";
import { RecoverySpacingPanel } from "@/components/RecoverySpacingPanel";

function dayName(key: string) { return key.split("-").slice(1).join("-") || key; }

export function WeeklyMuscleVolumePanel({ plan, prescriptions, goal }: { plan: WeeklyPlan; prescriptions: WeeklyPrescriptionStore; goal: TrainingGoal }) {
  const volumes = getWeeklyMuscleVolume(plan, prescriptions, goal);
  const savedDays = Object.values(plan).filter((workout) => workout.length).length;
  const max = Math.max(12, ...volumes.map((volume) => volume.equivalentSets));
  const featured = volumes.slice(0, 8);
  return <section className="weekly-volume-panel" aria-label="Weekly per-muscle volume"><div className="weekly-volume-head"><div><p className="metric-label">Saved-week exposure</p><h3>Muscle volume map</h3><p>{savedDays ? `${savedDays} saved training day${savedDays === 1 ? "" : "s"} contribute to the estimate.` : "Save a training day to begin the weekly volume map."}</p></div><div><BarChart3 className="h-5 w-5" /><strong>{volumes.reduce((total, volume) => total + volume.equivalentSets, 0).toFixed(1)}</strong><small>estimated muscle-set exposure</small></div></div><div className="weekly-volume-legend"><span><i className="weekly-volume-direct" />Direct working sets</span><span><i className="weekly-volume-support" />Supporting exposure (0.5 model weight)</span></div>{featured.length ? <div className="weekly-volume-list">{featured.map((volume) => { const status = getVolumeStatus(volume); return <article key={volume.muscle}><div className="weekly-volume-row"><div><strong>{volume.label}</strong><small>{volume.directSets} direct · {volume.supportSets} supporting</small></div><span className={`weekly-volume-status weekly-volume-status-${status.tone}`}>{status.label}</span><b>{volume.equivalentSets}</b></div><div className="weekly-volume-track" aria-label={`${volume.label}: ${volume.equivalentSets} estimated sets`}><i className="weekly-volume-bar-direct" style={{ width: `${Math.min(100, (volume.directSets / max) * 100)}%` }} /><i className="weekly-volume-bar-support" style={{ width: `${Math.min(100, (volume.equivalentSets / max) * 100)}%` }} /></div><p className="weekly-volume-days">{Object.entries(volume.daySets).map(([key, sets]) => <span key={key}>{dayName(key)} <b>{sets}</b></span>)}</p></article>; })}</div> : <div className="weekly-volume-empty"><Layers3 className="h-4 w-4" /> Save the current draft to a day of the weekly map to calculate exposure.</div>}<details className="weekly-volume-details"><summary>How this estimate works <ChevronDown className="h-4 w-4" /></summary><p>Primary-muscle sets count at 1.0. Supporting exposure uses a fixed 0.5 bookkeeping weight so assisting muscles are not shown as full direct sets; it is not a measured physiological fraction. The map uses the saved day prescription when available, otherwise the current goal default. It is a planning estimate—not a measure of recovery, hypertrophy, or clinical readiness.</p></details><RecoverySpacingPanel plan={plan} prescriptions={prescriptions} goal={goal} /></section>;
}
