/** Modern Kinetic Field Manual: concise coach diagnostics with a clear estimate-versus-measurement boundary. */
import type { Exercise } from "@/lib/exerciseCatalog";
import { getWorkoutDiagnostics, type ExerciseSettings, type TrainingGoal } from "@/lib/workoutPlanner";

export function WorkoutHealthPanel({ workout, prescriptions, settings, goal = "Athleticism", gymMinutes = 60 }: { workout: Exercise[]; prescriptions: Record<number, string>; settings: Record<number, ExerciseSettings>; goal?: TrainingGoal; gymMinutes?: number }) {
  const diagnostics = getWorkoutDiagnostics(workout, prescriptions, settings, goal, gymMinutes);
  const signal = diagnostics.fatigueExposure >= 72 ? "High" : diagnostics.fatigueExposure >= 52 ? "Moderate" : "Managed";
  return <section className="workout-health-panel" aria-label="Session diagnostics"><div className="workout-health-head"><div><p className="metric-label !text-[#9cb4d0]">Session diagnostics</p><h3>Coach scan</h3></div><span className={`health-signal health-signal-${signal.toLowerCase()}`}>{signal} fatigue</span></div><div className="health-stat-grid health-stat-grid-compact"><div><strong>{diagnostics.totalSets}</strong><span>working sets</span></div><div><strong>~{diagnostics.estimatedMinutes}m</strong><span>time estimate</span></div><div><strong>{diagnostics.redundancy}%</strong><span>overlap</span></div></div><div className="health-block"><p className="metric-label !text-[#9cb4d0]">Next coaching cue</p><p className="health-prompt">{diagnostics.prompts[0] || diagnostics.gymTimeBudget.scopeCue}</p></div><details className="health-details"><summary>Open planning detail</summary><div className="health-detail-stack"><div className="health-block"><p className="metric-label !text-[#9cb4d0]">Time budget / {diagnostics.gymTimeBudget.label}</p><p className="health-prompt">{diagnostics.gymTimeBudget.scopeCue}</p></div><div className="health-block"><p className="metric-label !text-[#9cb4d0]">Goal band / {diagnostics.target.goal}</p><p className="health-prompt">{diagnostics.target.sessionSetBand[0]}–{diagnostics.target.sessionSetBand[1]} working sets is the current planning band. {diagnostics.target.workingSetCue}.</p><p className="health-boundary !px-0 !pb-0">{diagnostics.target.repetitionCue} {diagnostics.target.restCue}</p></div><div className="health-block"><p className="metric-label !text-[#9cb4d0]">Pattern balance</p><div className="health-chip-row">{diagnostics.dominantPatterns.length ? diagnostics.dominantPatterns.map(([pattern, count]) => <span key={pattern}>{pattern} <b>{count}</b></span>) : <span>Awaiting exercises</span>}</div></div><div className="health-block"><p className="metric-label !text-[#9cb4d0]">Additional cues</p>{diagnostics.prompts.slice(1).map((prompt) => <p key={prompt} className="health-prompt">{prompt}</p>)}<p className="health-boundary !px-0 !pb-0">Set × RPE load: {diagnostics.sessionLoad}. Planning estimates are not measured recovery or medical-readiness scores.</p></div></div></details></section>;
}
