/** Gym Optimizer Workout Genome: program-aware coverage and redundancy snapshot for the active session. */
import { AlertTriangle, Layers3, Sparkles } from "lucide-react";
import type { Exercise } from "@/lib/exerciseCatalog";
import { getWorkoutGenome } from "@/lib/exerciseGenome";

export function WorkoutGenomeSummary({ workout }: { workout: Exercise[] }) {
  const genome = getWorkoutGenome(workout);
  return <div className="workout-genome"><div className="flex items-start justify-between gap-3"><div><p className="metric-label !text-[#9db8df]">Workout Genome / stack analysis</p><p className="mt-1 font-display text-2xl font-bold uppercase leading-none text-white">Coverage before volume</p></div><Layers3 className="h-5 w-5 text-[#79a9ff]" /></div><div className="mt-4 grid grid-cols-3 divide-x divide-white/10 border-y border-white/10"><div className="py-3 pr-3"><p className="metric-label !text-[#95a8c0]">Exercises</p><p className="mt-1 font-display text-2xl font-bold text-white">{workout.length}</p></div><div className="px-3 py-3"><p className="metric-label !text-[#95a8c0]">Redundancy</p><p className="mt-1 font-display text-2xl font-bold text-[#7eafff]">{genome.redundancy}</p></div><div className="px-3 py-3"><p className="metric-label !text-[#95a8c0]">Gaps</p><p className="mt-1 font-display text-2xl font-bold text-[#dbe8ff]">{genome.gaps.length}</p></div></div><div className="mt-4 grid gap-3 md:grid-cols-2"><div><p className="metric-label !text-[#95a8c0]">Dominant exposure</p><div className="mt-2 flex flex-wrap gap-1.5">{genome.dominantPatterns.length ? genome.dominantPatterns.map(([label, count]) => <span key={label} className="workout-genome-tag">{label} · {count}</span>) : <span className="text-xs text-[#a7b5c7]">Add an exercise to inspect coverage.</span>}</div></div><div><p className="metric-label !text-[#95a8c0]">What may be missing</p><div className="mt-2 flex flex-wrap gap-1.5">{genome.gaps.length ? genome.gaps.slice(0, 4).map((gap) => <span key={gap} className="workout-genome-gap">{gap}</span>) : <span className="text-xs text-[#a7b5c7]">Core movement families are represented.</span>}</div></div></div>{workout.length > 1 && <div className="mt-4 flex gap-2 border-t border-white/10 pt-3 text-[11px] leading-5 text-[#c5d5e9]">{genome.redundancy > 62 ? <><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-[#9fc4ff]" />This stack repeats similar muscle and movement demand. Inspect exercise Genomes to decide whether the overlap is intentional.</> : <><Sparkles className="mt-0.5 h-4 w-4 shrink-0 text-[#79a9ff]" />This stack has a relatively broad movement profile. Add only what improves the missing exposure for today&apos;s goal.</>}</div>}</div>;
}
