import { CalendarDays, CheckCircle2, History } from "lucide-react";
import { formatSessionDate, formatSessionYear, getSessionHistorySummary, type SessionHistoryItem } from "@/lib/sessionHistory";
import "../session-history-timeline.css";

export function WorkoutHistoryTimeline({ sessions, isLoading }: { sessions: SessionHistoryItem[]; isLoading: boolean }) {
  const completed = sessions.filter((session) => (session as SessionHistoryItem & { status?: string }).status === "completed");
  const summary = getSessionHistorySummary(completed);
  return <section className="workout-history-timeline" aria-label="Completed workout session history"><div className="workout-history-timeline-head"><div><p className="metric-label">Completed history</p><h4>Training timeline</h4><p>{summary.sessions ? `${summary.sessions} saved session${summary.sessions === 1 ? "" : "s"} · ${summary.completedSets} completed sets` : "Completed sessions will appear here after you finish a workout."}</p></div><History className="h-4 w-4" /></div>{isLoading ? <p className="workout-history-timeline-empty">Loading your saved sessions…</p> : completed.length ? <><div className="workout-history-stats"><span><b>{summary.sessions}</b> sessions</span><span><b>{summary.completedSets}</b> logged sets</span><span><b>{summary.exercises}</b> exercise entries</span></div><ol className="workout-history-timeline-list">{completed.slice(0, 8).map((session) => <li key={session.id}><time><strong>{formatSessionDate(session.startedAt)}</strong><small>{formatSessionYear(session.startedAt)}</small></time><i><CheckCircle2 className="h-3.5 w-3.5" /></i><div><strong>{session.title}</strong><small>{session.dayLabel || "Saved training day"}{session.goal ? ` · ${session.goal}` : ""}</small><span>{session.completedSetCount} completed set{session.completedSetCount === 1 ? "" : "s"} · {session.exerciseCount} exercise{session.exerciseCount === 1 ? "" : "s"}</span></div></li>)}</ol></> : <div className="workout-history-timeline-empty"><CalendarDays className="h-4 w-4" /> Complete a logged workout to create your first timeline entry.</div>}</section>;
}
