// Scans scripts/higgsfield/catalog/models/*.ts and writes
// scripts/higgsfield/catalog/models.generated.ts (the MODELS barrel).
//
// Vendored from higgsfield-ai/app-templates (scripts/sync-models.mjs) with the
// registry.json output removed: this repo is not a shadcn registry. Run it after
// adding or removing a model file; never hand-edit the barrel.
//
//   node scripts/higgsfield/sync-models.mjs
import { existsSync, mkdirSync, readdirSync, watch, writeFileSync, readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const ROOT = dirname(fileURLToPath(import.meta.url));
const MODELS_DIR = join(ROOT, "catalog/models");
const BARREL = join(ROOT, "catalog/models.generated.ts");

export function syncModels() {
  // A bare install ships no model files; an empty barrel is still a valid catalog.
  mkdirSync(MODELS_DIR, { recursive: true });
  const names = readdirSync(MODELS_DIR)
    .filter((file) => file.endsWith(".ts") && !file.endsWith(".d.ts"))
    .map((file) => file.slice(0, -3))
    .sort();

  const barrel = renderBarrel(names);
  const changed = writeIfChanged(BARREL, barrel);
  return { names, changed: Boolean(changed) };
}

/** Dev only: re-sync when a model file is added or removed (e.g. by `shadcn add`). */
export function watchModels() {
  mkdirSync(MODELS_DIR, { recursive: true });
  let timer;
  watch(MODELS_DIR, (_event, file) => {
    if (!file || !file.endsWith(".ts")) return;
    clearTimeout(timer);
    timer = setTimeout(() => {
      const { names, changed } = syncModels();
      if (changed) console.log(`[models] ${names.length} model files, barrel updated`);
    }, 150);
  }).unref();
}

function renderBarrel(names) {
  const imports = names.map((name, i) => `import m${i} from "./models/${name}";`).join("\n");
  const list = names.map((_, i) => `m${i}`).join(", ");
  return `// Generated by scripts/higgsfield/sync-models.mjs from catalog/models/*. Do not edit.
import type { ModelEntry } from "./types";

${imports}

const LAST = Number.MAX_SAFE_INTEGER;

const installed: (ModelEntry | ModelEntry[])[] = [${list}];

export const MODELS: readonly ModelEntry[] = installed
  .flat()
  .sort((a, b) => (a.order ?? LAST) - (b.order ?? LAST));
`;
}

function matchAll(source, regex) {
  return [...source.matchAll(regex)].map((match) => match[1]);
}

function writeIfChanged(path, content) {
  if (existsSync(path) && readFileSync(path, "utf8") === content) return 0;
  writeFileSync(path, content);
  return 1;
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  const { names, changed } = syncModels();
  console.log(`[models] ${names.length} model files${changed ? ", updated barrel" : ", up to date"}`);
}
